# Preface {.unnumbered}

This web-book is derived from my lecture slides for the Spring 2023 session of Epidemiology 204: "Quantitative Epidemiology III: Statistical Models", at UC Davis.

I have drawn these materials from many sources, including but not limited to:

-   "An Introduction to Generalized Linear Models" (4th edition, 2018)
by Annette J. Dobson and Adrian G. Barnett (<https://doi.org/10.1201/9781315182780>)

- David Rocke's materiels from the 2021 edition of Epi 204 (<https://dmrocke.ucdavis.edu/Class/EPI204-Spring-2021/EPI204-Spring-2021.html>)

- "Regression Methods in Biostatistics" (2nd edition, 2012) by Eric Vittinghoff , David V. Glidden , Stephen C. Shiboski , and Charles E. McCulloch  (<https://link.springer.com/book/10.1007/978-1-4614-1353-0>)

## License {.unnumbered}

This book is licensed to you under [Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License][http://creativecommons.org/licenses/by-nc-nd/4.0/].

The code samples in this book are licensed under [Creative Commons CC0 1.0 Universal (CC0 1.0)][https://creativecommons.org/publicdomain/zero/1.0/], i.e. public domain.
