<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Regression Models for Epidemiology - 6&nbsp; Proportional Hazards Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./coxph-model-building.html" rel="next">
<link href="./intro-to-survival-analysis.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-W625DGE908"></script><script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-W625DGE908', { 'anonymize_ip': true});
</script><script type="application/json" class="js-hypothesis-config">
{
  "theme": "clean",
  "openSidebar": false,
  "enableExperimentalNewNoteButton": true
}
</script><script async="" src="https://hypothes.is/embed.js"></script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><link rel="stylesheet" href="custom.scss">
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./time-to-event-models.html">Time to Event Models</a></li><li class="breadcrumb-item"><a href="./proportional-hazards-models.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Proportional Hazards Models</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Regression Models for Epidemiology</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/d-morrison/rme" rel="" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./Regression-Models-for-Epidemiology.pdf" rel="" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro-to-GLMs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./glms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Generalized Linear Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Linear-models-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Linear (Gaussian) Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Logistic Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./count-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Models for Count Outcomes</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./time-to-event-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Time to Event Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro-to-survival-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Introduction to Survival Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./proportional-hazards-models.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Proportional Hazards Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./coxph-model-building.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Building Cox Proportional Hazards models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./parametric-survival-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Parametric survival models</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Probability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro-MLEs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Introduction to Maximum Likelihood Inference</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#configuring-r" id="toc-configuring-r" class="nav-link active" data-scroll-target="#configuring-r">Configuring R</a></li>
  <li>
<a href="#the-proportional-hazards-model" id="toc-the-proportional-hazards-model" class="nav-link" data-scroll-target="#the-proportional-hazards-model"><span class="header-section-number">6.1</span> The proportional hazards model</a>
  <ul class="collapse">
<li><a href="#background-on-the-proportional-hazards-model" id="toc-background-on-the-proportional-hazards-model" class="nav-link" data-scroll-target="#background-on-the-proportional-hazards-model"><span class="header-section-number">6.1.1</span> Background on the Proportional Hazards Model</a></li>
  <li><a href="#coxs-proportional-hazards-model" id="toc-coxs-proportional-hazards-model" class="nav-link" data-scroll-target="#coxs-proportional-hazards-model"><span class="header-section-number">6.1.2</span> Cox’s Proportional Hazards Model</a></li>
  <li><a href="#additional-properties-of-the-proportional-hazards-model" id="toc-additional-properties-of-the-proportional-hazards-model" class="nav-link" data-scroll-target="#additional-properties-of-the-proportional-hazards-model"><span class="header-section-number">6.1.3</span> Additional properties of the proportional hazards model</a></li>
  <li><a href="#testing-the-proportional-hazards-assumption" id="toc-testing-the-proportional-hazards-assumption" class="nav-link" data-scroll-target="#testing-the-proportional-hazards-assumption"><span class="header-section-number">6.1.4</span> Testing the proportional hazards assumption</a></li>
  <li><a href="#smoothed-hazard-functions" id="toc-smoothed-hazard-functions" class="nav-link" data-scroll-target="#smoothed-hazard-functions"><span class="header-section-number">6.1.5</span> Smoothed hazard functions</a></li>
  <li><a href="#fitting-the-proportional-hazards-model" id="toc-fitting-the-proportional-hazards-model" class="nav-link" data-scroll-target="#fitting-the-proportional-hazards-model"><span class="header-section-number">6.1.6</span> Fitting the Proportional Hazards Model</a></li>
  </ul>
</li>
  <li>
<a href="#cox-model-for-the-bmt-data" id="toc-cox-model-for-the-bmt-data" class="nav-link" data-scroll-target="#cox-model-for-the-bmt-data"><span class="header-section-number">6.2</span> Cox Model for the <code>bmt</code> data</a>
  <ul class="collapse">
<li><a href="#fit-the-model" id="toc-fit-the-model" class="nav-link" data-scroll-target="#fit-the-model"><span class="header-section-number">6.2.1</span> Fit the model</a></li>
  <li><a href="#survival-curves-from-the-cox-model" id="toc-survival-curves-from-the-cox-model" class="nav-link" data-scroll-target="#survival-curves-from-the-cox-model"><span class="header-section-number">6.2.2</span> Survival Curves from the Cox Model</a></li>
  <li><a href="#examining-survfit" id="toc-examining-survfit" class="nav-link" data-scroll-target="#examining-survfit"><span class="header-section-number">6.2.3</span> Examining <code>survfit</code></a></li>
  </ul>
</li>
  <li>
<a href="#adjustment-for-ties-optional" id="toc-adjustment-for-ties-optional" class="nav-link" data-scroll-target="#adjustment-for-ties-optional"><span class="header-section-number">6.3</span> Adjustment for Ties (optional)</a>
  <ul class="collapse">
<li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"><span class="header-section-number">6.3.1</span> </a></li>
  </ul>
</li>
  </ul><div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/d-morrison/rme/edit/main/proportional-hazards-models.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/d-morrison/rme/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">
<span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Proportional Hazards Models</span>
</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">Last modified: 2023-09-25: 18:06:29 (PM)</p>
    </div>
  </div>
  
    
  </div>
  

</header><section id="configuring-r" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="configuring-r">Configuring R</h3>
<p>Functions from these packages will be used throughout this document:</p>
<div class="cell" data-hash="proportional-hazards-models_cache/html/packages_a23d073f9e4e450ba138bd9b49332e0c">
<details><summary>Code</summary><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://rapporter.github.io/pander/">pander</a></span><span class="op">)</span> <span class="co"># format tables for markdown</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span> <span class="co"># graphics</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/jonocarroll/ggeasy">ggeasy</a></span><span class="op">)</span> <span class="co"># help with graphics</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span> <span class="co"># manipulate data</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://haven.tidyverse.org">haven</a></span><span class="op">)</span> <span class="co"># import Stata files</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://yihui.org/knitr/">knitr</a></span><span class="op">)</span> <span class="co"># format R output for markdown</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyr.tidyverse.org">tidyr</a></span><span class="op">)</span> <span class="co"># Tools to help to create tidy data</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://plotly-r.com">plotly</a></span><span class="op">)</span> <span class="co"># interactive graphics</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">dobson</span><span class="op">)</span> <span class="co"># datasets from Dobson and Barnett 2018</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://easystats.github.io/parameters/">parameters</a></span><span class="op">)</span> <span class="co"># format model output tables for markdown</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://conflicted.r-lib.org/">conflicted</a></span><span class="op">)</span> <span class="co"># check for conflicting function definitions</span></span>
<span><span class="fu"><a href="https://conflicted.r-lib.org/reference/conflicts_prefer.html">conflicts_prefer</a></span><span class="op">(</span><span class="fu">dplyr</span><span class="fu">::</span><span class="va"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Here are some R settings I use in this document:</p>
<div class="cell" data-hash="proportional-hazards-models_cache/html/options_e6408b7d51e77acc1d69040371e3d7e8">
<details><summary>Code</summary><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/rm.html">rm</a></span><span class="op">(</span>list <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ls.html">ls</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="co"># delete any data that's already loaded into R</span></span>
<span><span class="fu">knitr</span><span class="fu">::</span><span class="va"><a href="https://rdrr.io/pkg/knitr/man/opts_chunk.html">opts_chunk</a></span><span class="op">$</span><span class="fu">set</span><span class="op">(</span>message <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="fu">pander</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pander/man/panderOptions.html">panderOptions</a></span><span class="op">(</span><span class="st">"table.emphasize.rownames"</span>, <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/options.html">options</a></span><span class="op">(</span><span class="st">'digits'</span> <span class="op">=</span> <span class="fl">4</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section><section id="the-proportional-hazards-model" class="level2" data-number="6.1"><h2 data-number="6.1" class="anchored" data-anchor-id="the-proportional-hazards-model">
<span class="header-section-number">6.1</span> The proportional hazards model</h2>
<section id="background-on-the-proportional-hazards-model" class="level3" data-number="6.1.1"><h3 data-number="6.1.1" class="anchored" data-anchor-id="background-on-the-proportional-hazards-model">
<span class="header-section-number">6.1.1</span> Background on the Proportional Hazards Model</h3>
<p>The exponential distribution has constant hazard:</p>
<p><span class="math display">\[
\begin{aligned}
f(t) &amp;= \lambda e^{-\lambda t}\\
S(t) &amp;= e^{-\lambda t}\\
h(t) &amp;= \lambda
\end{aligned}
\]</span></p>
<p>Let’s make two generalizations. First, we let the hazard depend on some covariates <span class="math inline">\(x_1,x_2, \dots, x_p\)</span>; we will indicate this dependence by extending our notation for hazard:</p>
<p><span class="math display">\[h(t|\boldsymbol x) \stackrel{\text{def}}{=}p(T=t|T\ge t, \boldsymbol X = \boldsymbol x)\]</span></p>
<p>Second, we let the base hazard depend on <span class="math inline">\(t\)</span>, but not on the covariates (for now). We can do this using either parametric or semi-parametric approaches.</p>
</section><section id="coxs-proportional-hazards-model" class="level3" data-number="6.1.2"><h3 data-number="6.1.2" class="anchored" data-anchor-id="coxs-proportional-hazards-model">
<span class="header-section-number">6.1.2</span> Cox’s Proportional Hazards Model</h3>
<p>The generalization is that the hazard function is</p>
<p><span class="math display">\[
\begin{aligned}
h(t|x)&amp;= h_0(t)\theta(x)\\
\theta(x) &amp;= \text{exp}\left\{\eta(x)\right\}\\
\eta(x) &amp;= x'\beta\\
&amp;\stackrel{\text{def}}{=}\beta_1x_1+\cdots+\beta_px_p
\end{aligned}
\]</span></p>
<p>The relationship between <span class="math inline">\(h(t|x)\)</span> and <span class="math inline">\(\eta(x)\)</span> has a log link (that is, <span class="math inline">\(\text{log}\left\{h(t|x)\right\} = \text{log}\left\{h_0(t)\right\} + \eta(x)\)</span>), as in a generalized linear model.</p>
<p>This model is <strong>semi-parametric</strong>, because the linear predictor depends on estimated parameters but the base hazard function is unspecified. There is no constant term in <span class="math inline">\(\eta(x)\)</span>, because it is absorbed in the base hazard.</p>
<p>Alternatively, we could define <span class="math inline">\(\beta_0(t) = \text{log}\left\{h_0(t)\right\}\)</span>, and then <span class="math inline">\(\eta(x,t) = \beta_0(t) + \beta_1x_1+\cdots+\beta_px_p\)</span>.</p>
<p>For two different individuals with covariate patterns <span class="math inline">\(\boldsymbol x_1\)</span> and <span class="math inline">\(\boldsymbol x_2\)</span>, the ratio of the hazard functions (a.k.a. <strong>hazard ratio</strong>, a.k.a. <strong>relative hazard</strong>) is:</p>
<p><span class="math display">\[
\begin{aligned}
\frac{h(t|\boldsymbol x_1)}{h(t|\boldsymbol x_2)}
&amp;=\frac{h_0(t)\theta(\boldsymbol x_1)}{h_0(t)\theta(\boldsymbol x_2)}\\
&amp;=\frac{\theta(\boldsymbol x_1)}{\theta(\boldsymbol x_2)}\\
\end{aligned}
\]</span></p>
<p>Under the proportional hazards model, this ratio (a.k.a. proportion) does not depend on <span class="math inline">\(t\)</span>. This property is a structural limitation of the model; it is called the <strong>proportional hazards assumption</strong>.</p>
<div id="def-pha" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 6.1 (proportional hazards) </strong></span>A conditional probability distribution <span class="math inline">\(p(T|X)\)</span> has <strong>proportional hazards</strong> if the hazard ratio <span class="math inline">\(h(t|\boldsymbol x_1)/h(t|\boldsymbol x_2)\)</span> does not depend on <span class="math inline">\(t\)</span>. Mathematically, it can be written as:</p>
<p><span class="math display">\[
\frac{h(t|\boldsymbol x_1)}{h(t|\boldsymbol x_2)}
= \theta(\boldsymbol x_1,\boldsymbol x_2)
\]</span></p>
</div>
<p>As we saw above, Cox’s proportional hazards model has this property, with <span class="math inline">\(\theta(\boldsymbol x_1,\boldsymbol x_2) = \frac{\theta(\boldsymbol x_1)}{\theta(\boldsymbol x_2)}\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>We are using two similar notations, <span class="math inline">\(\theta(\boldsymbol x_1,\boldsymbol x_2)\)</span> and <span class="math inline">\(\theta(\boldsymbol x)\)</span>. We can link these notations if we define <span class="math inline">\(\theta(\boldsymbol x) \stackrel{\text{def}}{=}\theta(\boldsymbol x, \boldsymbol 0)\)</span> and <span class="math inline">\(\theta(\boldsymbol 0) = 1\)</span>.</p>
</div>
</div>
<p>It also has additional notable properties:</p>
<p><span class="math display">\[
\begin{aligned}
\frac{h(t|\boldsymbol x_1)}{h(t|\boldsymbol x_2)}
&amp;=\frac{\theta(\boldsymbol x_1)}{\theta(\boldsymbol x_2)}\\
&amp;=\frac{\text{exp}\left\{\eta(\boldsymbol x_1)\right\}}{\text{exp}\left\{\eta(\boldsymbol x_2)\right\}}\\
&amp;=\text{exp}\left\{\eta(\boldsymbol x_1)-\eta(\boldsymbol x_2)\right\}\\
&amp;=\text{exp}\left\{\boldsymbol x_1'\beta-\boldsymbol x_2'\beta\right\}\\
&amp;=\text{exp}\left\{(\boldsymbol x_1 - \boldsymbol x_2)'\beta\right\}\\
\end{aligned}
\]</span></p>
<p>Hence on the log scale, we have:</p>
<p><span class="math display">\[
\begin{aligned}
\text{log}\left\{\frac{h(t|\boldsymbol x_1)}{h(t|\boldsymbol x_2)}\right\}
&amp;=\eta(\boldsymbol x_1)-\eta(\boldsymbol x_2)\\
&amp;= \boldsymbol x_1'\beta-\boldsymbol x_2'\beta\\
&amp;= (\boldsymbol x_1 - \boldsymbol x_2)'\beta
\end{aligned}
\]</span></p>
<p>If only one covariate <span class="math inline">\(x_j\)</span> is changing, then:</p>
<p><span class="math display">\[
\begin{aligned}
\text{log}\left\{\frac{h(t|\boldsymbol x_1)}{h(t|\boldsymbol x_2)}\right\}
&amp;=  (x_{1j} - x_{2j}) \cdot \beta_j\\
&amp;\propto (x_{1j} - x_{2j})
\end{aligned}
\]</span></p>
<p>That is, under Cox’s model <span class="math inline">\(h(t|\boldsymbol x) = h_0(t)\text{exp}\left\{\boldsymbol x'\beta\right\}\)</span>, the log of the hazard ratio is proportional to the difference in <span class="math inline">\(x_j\)</span>, with the proportionality coefficient equal to <span class="math inline">\(\beta_j\)</span>.</p>
<p>Further,</p>
<p><span class="math display">\[
\begin{aligned}
\text{log}\left\{h(t|\boldsymbol x)\right\}
&amp;=\text{log}\left\{h_0(t)\right\}  + x'\beta
\end{aligned}
\]</span></p>
<p>That is, the covariate effects are additive on the log-hazard scale.</p>
<p>See also:</p>
<p><a href="https://en.wikipedia.org/wiki/Proportional_hazards_model#Why_it_is_called_%22proportional%22" class="uri">https://en.wikipedia.org/wiki/Proportional_hazards_model#Why_it_is_called_%22proportional%22</a></p>
</section><section id="additional-properties-of-the-proportional-hazards-model" class="level3" data-number="6.1.3"><h3 data-number="6.1.3" class="anchored" data-anchor-id="additional-properties-of-the-proportional-hazards-model">
<span class="header-section-number">6.1.3</span> Additional properties of the proportional hazards model</h3>
<p>If <span class="math inline">\(h(t|x)= h_0(t)\theta(x)\)</span>, then:</p>
<section id="cumulative-hazards-are-also-proportional-to-h_0t" class="level4"><h4 class="anchored" data-anchor-id="cumulative-hazards-are-also-proportional-to-h_0t">Cumulative hazards are also proportional to <span class="math inline">\(H_0(t)\)</span>
</h4>
<p><span class="math display">\[
\begin{aligned}
H(t|x)
&amp;\stackrel{\text{def}}{=}\int_{u=0}^t h(u)du\\
&amp;= \int_{u=0}^t h_0(u)\theta(x)du\\
&amp;= \theta(x)\int_{u=0}^t h_0(u)du\\
&amp;= \theta(x)H_0(t)
\end{aligned}
\]</span></p>
<p>where <span class="math inline">\(H_0(t) \stackrel{\text{def}}{=}H(t|0) = \int_{u=0}^t h_0(u)du\)</span>.</p>
</section><section id="survival-functions-are-exponential-multiples-of-s_0t" class="level4"><h4 class="anchored" data-anchor-id="survival-functions-are-exponential-multiples-of-s_0t">Survival functions are exponential multiples of <span class="math inline">\(S_0(t)\)</span>
</h4>
<p><span class="math display">\[
\begin{aligned}
S(t|x)
&amp;= \text{exp}\left\{-H(t|x)\right\}\\
&amp;= \text{exp}\left\{-\theta(x)\cdot H_0(t)\right\}\\
&amp;= \left(\text{exp}\left\{- H_0(t)\right\}\right)^{\theta(x)}\\
&amp;= \left(S_0(t)\right)^{\theta(x)}\\
\end{aligned}
\]</span></p>
<p>where <span class="math inline">\(S_0(t) \stackrel{\text{def}}{=}P(T\ge t | \boldsymbol X = 0)\)</span> is the survival function for an individual whose covariates are all equal to their default values.</p>
</section></section><section id="testing-the-proportional-hazards-assumption" class="level3" data-number="6.1.4"><h3 data-number="6.1.4" class="anchored" data-anchor-id="testing-the-proportional-hazards-assumption">
<span class="header-section-number">6.1.4</span> Testing the proportional hazards assumption</h3>
<p>The Nelson-Aalen estimate of the cumulative hazard is usually used for estimates of the hazard and often the cumulative hazard.</p>
<p>If the hazards of the three groups are proportional, that means that the ratio of the hazards is constant over <span class="math inline">\(t\)</span>. We can test this using the ratios of the estimated cumulative hazards, which also would be proportional, as shown above.</p>
<div class="cell" data-hash="proportional-hazards-models_cache/html/unnamed-chunk-2_b89e82f38723fe7359806e616b7c7ac2">
<details><summary>Code</summary><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">KMsurv</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/therneau/survival">survival</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">bmt</span><span class="op">)</span></span>
<span></span>
<span><span class="va">bmt</span> <span class="op">=</span> </span>
<span>  <span class="va">bmt</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    group <span class="op">=</span> </span>
<span>      <span class="va">group</span> <span class="op">|&gt;</span> </span>
<span>      <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span></span>
<span>        labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"ALL"</span>,<span class="st">"Low Risk AML"</span>,<span class="st">"High Risk AML"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">nafit</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/survfit.html">survfit</a></span><span class="op">(</span></span>
<span>  formula <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">t2</span>,<span class="va">d3</span><span class="op">)</span> <span class="op">~</span> <span class="va">group</span>,</span>
<span>  type <span class="op">=</span> <span class="st">"fleming-harrington"</span>,</span>
<span>  data <span class="op">=</span> <span class="va">bmt</span><span class="op">)</span></span>
<span></span>
<span><span class="va">bmt_curves</span> <span class="op">=</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>timevec <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">1000</span><span class="op">)</span></span>
<span><span class="va">sf1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/with.html">with</a></span><span class="op">(</span><span class="va">nafit</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, <span class="fu"><a href="https://rdrr.io/r/stats/stepfun.html">stepfun</a></span><span class="op">(</span><span class="va">time</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="va">surv</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">sf2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/with.html">with</a></span><span class="op">(</span><span class="va">nafit</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>, <span class="fu"><a href="https://rdrr.io/r/stats/stepfun.html">stepfun</a></span><span class="op">(</span><span class="va">time</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="va">surv</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">sf3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/with.html">with</a></span><span class="op">(</span><span class="va">nafit</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span>, <span class="fu"><a href="https://rdrr.io/r/stats/stepfun.html">stepfun</a></span><span class="op">(</span><span class="va">time</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="va">surv</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">bmt_curves</span> <span class="op">=</span> </span>
<span>  <span class="va">bmt_curves</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    cumhaz1 <span class="op">=</span> <span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="fu">sf1</span><span class="op">(</span><span class="va">timevec</span><span class="op">)</span><span class="op">)</span>,</span>
<span>    cumhaz2 <span class="op">=</span> <span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="fu">sf2</span><span class="op">(</span><span class="va">timevec</span><span class="op">)</span><span class="op">)</span>,</span>
<span>    cumhaz3 <span class="op">=</span> <span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="fu">sf3</span><span class="op">(</span><span class="va">timevec</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-hash="proportional-hazards-models_cache/html/unnamed-chunk-3_c2b2e8ea09159c4bf770099f5d8cf87d">
<details><summary>Code</summary><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="va">bmt_rel_hazard_plot</span> <span class="op">=</span> </span>
<span>  <span class="va">bmt_curves</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span></span>
<span>      x <span class="op">=</span> <span class="va">timevec</span>,</span>
<span>      y <span class="op">=</span> <span class="va">cumhaz1</span><span class="op">/</span><span class="va">cumhaz2</span><span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>col <span class="op">=</span> <span class="st">"ALL/Low Risk AML"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span><span class="op">(</span><span class="st">"Hazard Ratio"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span><span class="op">(</span><span class="st">"Time"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/lims.html">ylim</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">6</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">cumhaz3</span><span class="op">/</span><span class="va">cumhaz1</span>, col <span class="op">=</span> <span class="st">"High Risk AML/ALL"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">cumhaz3</span><span class="op">/</span><span class="va">cumhaz2</span>, col <span class="op">=</span> <span class="st">"High Risk AML/Low Risk AML"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>colour <span class="op">=</span> <span class="st">"Comparison"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>legend.position<span class="op">=</span><span class="st">"bottom"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">bmt_rel_hazard_plot</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><figcaption class="figure-caption">Hazard Ratios by Disease Group</figcaption><p><img src="proportional-hazards-models_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can zoom in on 30-300 days to take a closer look:</p>
<div class="cell" data-hash="proportional-hazards-models_cache/html/unnamed-chunk-4_7af6f00fce3c7ebace533becb9ae79e4">
<details><summary>Code</summary><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">bmt_rel_hazard_plot</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/lims.html">xlim</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">30</span>,<span class="fl">300</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><figcaption class="figure-caption">Hazard Ratios by Disease Group (30-300 Days)</figcaption><p><img src="proportional-hazards-models_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section><section id="smoothed-hazard-functions" class="level3" data-number="6.1.5"><h3 data-number="6.1.5" class="anchored" data-anchor-id="smoothed-hazard-functions">
<span class="header-section-number">6.1.5</span> Smoothed hazard functions</h3>
<p>The Nelson-Aalen estimate of the cumulative hazard is usually used for estimates of the hazard. Since the hazard is the derivative of the cumulative hazard, we need a smooth estimate of the cumulative hazard, which is provided by smoothing the step-function cumulative hazard.</p>
<p>The R package <code>muhaz</code> handles this for us. What we are looking for is whether the hazard function is more or less the same shape, increasing, decreasing, constant, etc. Are the hazards “proportional”?</p>
<div class="cell" data-hash="proportional-hazards-models_cache/html/unnamed-chunk-5_d33d47bfab1ff926ca806efae309b748">
<details><summary>Code</summary><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/survival/man/survfit.html">survfit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">t2</span>,<span class="va">d3</span><span class="op">)</span><span class="op">~</span><span class="va">group</span>,data<span class="op">=</span><span class="va">bmt</span><span class="op">)</span>,</span>
<span>  col<span class="op">=</span><span class="fl">1</span><span class="op">:</span><span class="fl">3</span>,</span>
<span>  lwd<span class="op">=</span><span class="fl">2</span>,</span>
<span>  fun<span class="op">=</span><span class="st">"cumhaz"</span>,</span>
<span>  mark.time <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/legend.html">legend</a></span><span class="op">(</span><span class="st">"bottomright"</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"ALL"</span>,<span class="st">"Low Risk AML"</span>,<span class="st">"High Risk AML"</span><span class="op">)</span>,col<span class="op">=</span><span class="fl">1</span><span class="op">:</span><span class="fl">3</span>,lwd<span class="op">=</span><span class="fl">2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><figcaption class="figure-caption">Disease-Free Cumulative Hazard by Disease Group</figcaption><p><img src="proportional-hazards-models_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-hash="proportional-hazards-models_cache/html/unnamed-chunk-6_c6470e2994453d1ee7d6bfcf36ff565d">
<details><summary>Code</summary><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">muhaz</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/muhaz/man/muhaz.html">muhaz</a></span><span class="op">(</span><span class="va">bmt</span><span class="op">$</span><span class="va">t2</span>,<span class="va">bmt</span><span class="op">$</span><span class="va">d3</span>,<span class="va">bmt</span><span class="op">$</span><span class="va">group</span><span class="op">==</span><span class="st">"High Risk AML"</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span>lwd<span class="op">=</span><span class="fl">2</span>,col<span class="op">=</span><span class="fl">3</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/muhaz/man/muhaz.html">muhaz</a></span><span class="op">(</span><span class="va">bmt</span><span class="op">$</span><span class="va">t2</span>,<span class="va">bmt</span><span class="op">$</span><span class="va">d3</span>,<span class="va">bmt</span><span class="op">$</span><span class="va">group</span><span class="op">==</span><span class="st">"ALL"</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span><span class="op">(</span>lwd<span class="op">=</span><span class="fl">2</span>,col<span class="op">=</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/muhaz/man/muhaz.html">muhaz</a></span><span class="op">(</span><span class="va">bmt</span><span class="op">$</span><span class="va">t2</span>,<span class="va">bmt</span><span class="op">$</span><span class="va">d3</span>,<span class="va">bmt</span><span class="op">$</span><span class="va">group</span><span class="op">==</span><span class="st">"Low Risk AML"</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span><span class="op">(</span>lwd<span class="op">=</span><span class="fl">2</span>,col<span class="op">=</span><span class="fl">2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/legend.html">legend</a></span><span class="op">(</span><span class="st">"topright"</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"ALL"</span>,<span class="st">"Low Risk AML"</span>,<span class="st">"High Risk AML"</span><span class="op">)</span>,col<span class="op">=</span><span class="fl">1</span><span class="op">:</span><span class="fl">3</span>,lwd<span class="op">=</span><span class="fl">2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><figcaption class="figure-caption">Smoothed Hazard Rate Estimates by Disease Group</figcaption><p><img src="proportional-hazards-models_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Group 3 was plotted first because it has the highest hazard.</p>
<p>We will see that except for an initial blip in the high risk AML group, the hazards look roughly proportional . They are all strongly decreasing.</p>
</section><section id="fitting-the-proportional-hazards-model" class="level3" data-number="6.1.6"><h3 data-number="6.1.6" class="anchored" data-anchor-id="fitting-the-proportional-hazards-model">
<span class="header-section-number">6.1.6</span> Fitting the Proportional Hazards Model</h3>
<p>How do we fit a proportional hazards regression model? We need to estimate the coefficients of the covariates, and we need to estimate the base hazard <span class="math inline">\(h_0(t)\)</span>. For the covariates, supposing for simplicity that there are no tied event times, let the event times for the whole data set be <span class="math inline">\(t_1, t_2,\ldots,t_D\)</span>. Let the risk set at time <span class="math inline">\(t_i\)</span> be <span class="math inline">\(R(t_i)\)</span> and</p>
<p><span class="math display">\[
\begin{aligned}
\eta(\boldsymbol{x}) &amp;= \beta_1x_{1}+\cdots+\beta_p x_{p}\\
\theta(\boldsymbol{x}) &amp;= e^{\eta(\boldsymbol{x})}\\
h(t|X=x)&amp;= h_0(t)e^{\eta(\boldsymbol{x})}=\theta(\boldsymbol{x}) h_0(t)
\end{aligned}
\]</span></p>
<p>Conditional on a single failure at time <span class="math inline">\(t\)</span>, the probability that the event is due to subject <span class="math inline">\(f\in R(t)\)</span> is approximately</p>
<p><span class="math display">\[
\begin{aligned}
\Pr(f \text{ fails}|\text{1 failure at } t)
&amp;= \frac{h_0(t)e^{\eta(\boldsymbol{x}_f)}}{\sum_{k \in R(t)}h_0(t)e^{\eta(\boldsymbol{x}_f)}}\\
&amp;=\frac{\theta(\boldsymbol{x}_f)}{\sum_{k \in R(t)} \theta(\boldsymbol{x}_k)}
\end{aligned}
\]</span></p>
<p>The logic behind this has several steps. We first fix (ex post) the failure times and note that in this discrete context, the probability <span class="math inline">\(p_j\)</span> that a subject <span class="math inline">\(j\)</span> in the risk set fails at time <span class="math inline">\(t\)</span> is just the hazard of that subject at that time.</p>
<p>If all of the <span class="math inline">\(p_j\)</span> are small, the chance that exactly one subject fails is</p>
<p><span class="math display">\[
\sum_{k\in R(t)}p_k\left[\prod_{m\in R(t), m\ne k} (1-p_m)\right]\approx\sum_{k\in R(t)}p_k
\]</span></p>
<p>If subject <span class="math inline">\(i\)</span> is the one who experiences the event of interest at time <span class="math inline">\(t_i\)</span>, then the <strong>partial likelihood</strong> is</p>
<p><span class="math display">\[
\mathcal L^*(\beta|T)=
\prod_i \frac{\theta(x_i)}{\sum_{k \in R(t_i)} \theta(\boldsymbol{x}_k)}
\]</span></p>
<p>and we can numerically maximize this with respect to the coefficients <span class="math inline">\(\boldsymbol{\beta}\)</span> that specify <span class="math inline">\(\eta(\boldsymbol{x}) = \boldsymbol{x}'\boldsymbol{\beta}\)</span>. When there are tied event times adjustments need to be made, but the likelihood is still similar. Note that we don’t need to know the base hazard to solve for the coefficients.</p>
<p>Once we have coefficient estimates <span class="math inline">\(\hat{\boldsymbol{\beta}} =(\hat \beta_1,\ldots,\hat\beta_p)\)</span>, this also defines <span class="math inline">\(\hat\eta(x)\)</span> and <span class="math inline">\(\hat\theta(x)\)</span> and then the estimated base cumulative hazard function is <span class="math display">\[\hat H(t)=
\sum_{t_i &lt; t} \frac{d_i}{\sum_{k\in R(t_i)} \theta(x_k)}\]</span> which reduces to the Nelson-Aalen estimate when there are no covariates. There are numerous other estimates that have been proposed as well.</p>
</section></section><section id="cox-model-for-the-bmt-data" class="level2" data-number="6.2"><h2 data-number="6.2" class="anchored" data-anchor-id="cox-model-for-the-bmt-data">
<span class="header-section-number">6.2</span> Cox Model for the <code>bmt</code> data</h2>
<section id="fit-the-model" class="level3" data-number="6.2.1"><h3 data-number="6.2.1" class="anchored" data-anchor-id="fit-the-model">
<span class="header-section-number">6.2.1</span> Fit the model</h3>
<div class="cell" data-hash="proportional-hazards-models_cache/html/unnamed-chunk-7_3a4f0d58199d0bd5572bccfba87d854a">
<details><summary>Code</summary><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">bmt.cox</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/coxph.html">coxph</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">t2</span>, <span class="va">d3</span><span class="op">)</span> <span class="op">~</span> <span class="va">group</span>, data <span class="op">=</span> <span class="va">bmt</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">bmt.cox</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(t2, d3) ~ group, data = bmt)

  n= 137, number of events= 83 

                       coef exp(coef) se(coef)       z Pr(&gt;|z|)  
groupLow Risk AML  -0.57420   0.56316  0.28730 -1.9986  0.04565 *
groupHigh Risk AML  0.38341   1.46728  0.26738  1.4340  0.15158  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

                   exp(coef) exp(-coef) lower .95 upper .95
groupLow Risk AML    0.56316    1.77570   0.32069   0.98896
groupHigh Risk AML   1.46728    0.68153   0.86881   2.47802

Concordance= 0.625  (se = 0.03 )
Likelihood ratio test= 13.45  on 2 df,   p=0.001
Wald test            = 13.03  on 2 df,   p=0.001
Score (logrank) test = 13.81  on 2 df,   p=0.001</code></pre>
</div>
</div>
<p>The table provides hypothesis tests comparing groups 2 and 3 to group 1. Group 3 has the highest hazard, so the most significant comparison is not directly shown.</p>
<p>The coefficient 0.3834 is on the log-hazard-ratio scale, as in log-risk-ratio. The next column gives the hazard ratio 1.4673, and a hypothesis (Wald) test.</p>
<p>The (not shown) group 3 vs.&nbsp;group 2 log hazard ratio is 0.3834 + 0.5742 = 0.9576. The hazard ratio is then exp(0.9576) or 2.605.</p>
<p>Inference on all coefficients and combinations can be constructed using <code>coef(bmt.cox)</code> and <code>vcov(bmt.cox)</code> as with logistic and poisson regression.</p>
<p><strong>Concordance</strong> is agreement of first failure between pairs of subjects and higher predicted risk between those subjects, omitting non-informative pairs.</p>
<p>The Rsquare value is Cox and Snell’s pseudo R-squared and is not very useful.</p>
<p><code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> prints three tests for whether the model with the group covariate is better than the one without</p>
<ul>
<li>
<code>Likelihood ratio test</code> (chi-squared)</li>
<li>
<code>Wald test</code> (also chi-squared), obtained by adding the squares of the z-scores</li>
<li>
<code>Score</code> = log-rank test, as with comparison of survival functions.</li>
</ul>
<p>The likelihood ratio test is probably best in smaller samples, followed by the Wald test.</p>
</section><section id="survival-curves-from-the-cox-model" class="level3" data-number="6.2.2"><h3 data-number="6.2.2" class="anchored" data-anchor-id="survival-curves-from-the-cox-model">
<span class="header-section-number">6.2.2</span> Survival Curves from the Cox Model</h3>
<p>We can take a look at the resulting group-specific curves:</p>
<div class="cell" data-hash="proportional-hazards-models_cache/html/unnamed-chunk-8_9ba533fcea7800cd2e14b8d7fbf5a82a">
<details><summary>Code</summary><div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#| fig-cap: "Survival Functions for Three Groups by KM and Cox Model"</span></span>
<span></span>
<span><span class="va">km_fit</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/survfit.html">survfit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">t2</span>, <span class="va">d3</span><span class="op">)</span> <span class="op">~</span> <span class="va">group</span>, data <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="va">bmt</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">cox_fit</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/survfit.html">survfit</a></span><span class="op">(</span></span>
<span>  <span class="va">bmt.cox</span>, </span>
<span>  newdata <span class="op">=</span> </span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>      group <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">bmt</span><span class="op">$</span><span class="va">group</span><span class="op">)</span>, </span>
<span>      row.names <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">bmt</span><span class="op">$</span><span class="va">group</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://rpkgs.datanovia.com/survminer/index.html">survminer</a></span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>KM <span class="op">=</span> <span class="va">km_fit</span>, Cox <span class="op">=</span> <span class="va">cox_fit</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">survminer</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/survminer/man/ggsurvplot.html">ggsurvplot</a></span><span class="op">(</span></span>
<span>    <span class="co"># facet.by = "group",</span></span>
<span>    legend <span class="op">=</span> <span class="st">"bottom"</span>, </span>
<span>    legend.title <span class="op">=</span> <span class="st">""</span>,</span>
<span>    combine <span class="op">=</span> <span class="cn">TRUE</span>, </span>
<span>    fun <span class="op">=</span> <span class="st">'pct'</span>, </span>
<span>    size <span class="op">=</span> <span class="fl">.5</span>,</span>
<span>    ggtheme <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span>, </span>
<span>    conf.int <span class="op">=</span> <span class="cn">FALSE</span>, </span>
<span>    censor <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/warning.html">suppressWarnings</a></span><span class="op">(</span><span class="op">)</span> <span class="co"># ggsurvplot() throws some warnings that aren't too worrying</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<p><img src="proportional-hazards-models_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>When we use <code><a href="https://rdrr.io/pkg/survival/man/survfit.html">survfit()</a></code> with a Cox model, we have to specify the covariate levels we are interested in; the argument <code>newdata</code> should include a <code>data.frame</code> with the same named columns as the predictors in the Cox model and one or more levels of each.</p>
<p>Otherwise (that is, if the <code>newdata</code> argument is missing), a curve is produced for a single “pseudo” subject with covariate values equal to the means component of the fit.</p>
<p>The resulting curve(s) almost never make sense, but the default remains due to an unwarranted attachment to the option shown by some users and by other packages.</p>
<p>Two particularly egregious examples are factor variables and interactions. Suppose one were studying interspecies transmission of a virus, and the data set has a factor variable with levels (“pig”, “chicken”) and about equal numbers of observations for each. The “mean” covariate level will be 0.5 – is this a flying pig?</p>
</section><section id="examining-survfit" class="level3" data-number="6.2.3"><h3 data-number="6.2.3" class="anchored" data-anchor-id="examining-survfit">
<span class="header-section-number">6.2.3</span> Examining <code>survfit</code>
</h3>
<div class="cell" data-hash="proportional-hazards-models_cache/html/unnamed-chunk-9_82dc1e8f78374b902bef46d40c17da6d">
<details><summary>Code</summary><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/survfit.html">survfit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">t2</span>, <span class="va">d3</span><span class="op">)</span><span class="op">~</span><span class="va">group</span>,data<span class="op">=</span><span class="va">bmt</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = Surv(t2, d3) ~ group, data = bmt)

                     n events median 0.95LCL 0.95UCL
group=ALL           38     24    418     194      NA
group=Low Risk AML  54     25   2204     704      NA
group=High Risk AML 45     34    183     115     456</code></pre>
</div>
</div>
<div class="cell" data-hash="proportional-hazards-models_cache/html/unnamed-chunk-10_14eb8beaf30d457ed4548e3452cd8c93">
<details><summary>Code</summary><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/survfit.html">survfit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">t2</span>, <span class="va">d3</span><span class="op">)</span><span class="op">~</span><span class="va">group</span>,data<span class="op">=</span><span class="va">bmt</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = Surv(t2, d3) ~ group, data = bmt)

                group=ALL 
 time n.risk n.event survival std.err lower 95% CI upper 95% CI
    1     38       1   0.9737 0.02597       0.9241       1.0000
   55     37       1   0.9474 0.03622       0.8790       1.0000
   74     36       1   0.9211 0.04374       0.8392       1.0000
   86     35       1   0.8947 0.04978       0.8023       0.9978
  104     34       1   0.8684 0.05484       0.7673       0.9828
  107     33       1   0.8421 0.05915       0.7338       0.9664
  109     32       1   0.8158 0.06289       0.7014       0.9488
  110     31       1   0.7895 0.06613       0.6699       0.9303
  122     30       2   0.7368 0.07143       0.6093       0.8910
  129     28       1   0.7105 0.07357       0.5800       0.8704
  172     27       1   0.6842 0.07541       0.5513       0.8492
  192     26       1   0.6579 0.07696       0.5231       0.8274
  194     25       1   0.6316 0.07825       0.4954       0.8052
  230     23       1   0.6041 0.07952       0.4667       0.7819
  276     22       1   0.5767 0.08051       0.4386       0.7582
  332     21       1   0.5492 0.08122       0.4110       0.7339
  383     20       1   0.5217 0.08167       0.3839       0.7091
  418     19       1   0.4943 0.08186       0.3573       0.6838
  466     18       1   0.4668 0.08179       0.3311       0.6581
  487     17       1   0.4394 0.08146       0.3055       0.6319
  526     16       1   0.4119 0.08086       0.2803       0.6052
  609     14       1   0.3825 0.08026       0.2535       0.5771
  662     13       1   0.3531 0.07930       0.2273       0.5483

                group=Low Risk AML 
 time n.risk n.event survival std.err lower 95% CI upper 95% CI
   10     54       1   0.9815 0.01835       0.9462       1.0000
   35     53       1   0.9630 0.02570       0.9139       1.0000
   48     52       1   0.9444 0.03117       0.8853       1.0000
   53     51       1   0.9259 0.03564       0.8586       0.9985
   79     50       1   0.9074 0.03945       0.8333       0.9881
   80     49       1   0.8889 0.04277       0.8089       0.9768
  105     48       1   0.8704 0.04571       0.7852       0.9647
  211     47       1   0.8519 0.04834       0.7622       0.9521
  219     46       1   0.8333 0.05072       0.7396       0.9389
  248     45       1   0.8148 0.05286       0.7175       0.9253
  272     44       1   0.7963 0.05481       0.6958       0.9113
  288     43       1   0.7778 0.05658       0.6744       0.8970
  381     42       1   0.7593 0.05818       0.6534       0.8823
  390     41       1   0.7407 0.05964       0.6326       0.8674
  414     40       1   0.7222 0.06095       0.6121       0.8521
  421     39       1   0.7037 0.06214       0.5919       0.8367
  481     38       1   0.6852 0.06320       0.5719       0.8210
  486     37       1   0.6667 0.06415       0.5521       0.8050
  606     36       1   0.6481 0.06499       0.5325       0.7889
  641     35       1   0.6296 0.06571       0.5132       0.7725
  704     34       1   0.6111 0.06634       0.4940       0.7560
  748     33       1   0.5926 0.06686       0.4750       0.7393
 1063     26       1   0.5698 0.06807       0.4509       0.7201
 1074     25       1   0.5470 0.06905       0.4271       0.7006
 2204      6       1   0.4558 0.10118       0.2950       0.7043

                group=High Risk AML 
 time n.risk n.event survival std.err lower 95% CI upper 95% CI
    2     45       1   0.9778 0.02197       0.9356       1.0000
   16     44       1   0.9556 0.03072       0.8972       1.0000
   32     43       1   0.9333 0.03718       0.8632       1.0000
   47     42       2   0.8889 0.04685       0.8017       0.9856
   48     40       1   0.8667 0.05067       0.7728       0.9719
   63     39       1   0.8444 0.05403       0.7449       0.9573
   64     38       1   0.8222 0.05699       0.7178       0.9419
   74     37       1   0.8000 0.05963       0.6913       0.9258
   76     36       1   0.7778 0.06197       0.6653       0.9092
   80     35       1   0.7556 0.06406       0.6399       0.8922
   84     34       1   0.7333 0.06592       0.6149       0.8746
   93     33       1   0.7111 0.06757       0.5903       0.8567
  100     32       1   0.6889 0.06901       0.5661       0.8383
  105     31       1   0.6667 0.07027       0.5422       0.8197
  113     30       1   0.6444 0.07136       0.5187       0.8006
  115     29       1   0.6222 0.07227       0.4955       0.7813
  120     28       1   0.6000 0.07303       0.4727       0.7617
  157     27       1   0.5778 0.07363       0.4501       0.7417
  162     26       1   0.5556 0.07407       0.4278       0.7215
  164     25       1   0.5333 0.07437       0.4058       0.7010
  168     24       1   0.5111 0.07452       0.3841       0.6802
  183     23       1   0.4889 0.07452       0.3626       0.6591
  242     22       1   0.4667 0.07437       0.3415       0.6378
  268     21       1   0.4444 0.07407       0.3206       0.6161
  273     20       1   0.4222 0.07363       0.3000       0.5943
  318     19       1   0.4000 0.07303       0.2797       0.5721
  363     18       1   0.3778 0.07227       0.2597       0.5496
  390     17       1   0.3556 0.07136       0.2399       0.5269
  422     16       1   0.3333 0.07027       0.2205       0.5039
  456     15       1   0.3111 0.06901       0.2014       0.4805
  467     14       1   0.2889 0.06757       0.1827       0.4569
  625     13       1   0.2667 0.06592       0.1643       0.4329
  677     12       1   0.2444 0.06406       0.1462       0.4086</code></pre>
</div>
</div>
<div class="cell" data-hash="proportional-hazards-models_cache/html/unnamed-chunk-11_355fe6af1c3252258786f07217c8414e">
<details><summary>Code</summary><div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/survfit.html">survfit</a></span><span class="op">(</span><span class="va">bmt.cox</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = bmt.cox)

       n events median 0.95LCL 0.95UCL
[1,] 137     83    422     268      NA</code></pre>
</div>
<details><summary>Code</summary><div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/survival/man/survfit.html">survfit</a></span><span class="op">(</span><span class="va">bmt.cox</span>, newdata <span class="op">=</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>group <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">bmt</span><span class="op">$</span><span class="va">group</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = bmt.cox, newdata = tibble(group = unique(bmt$group)))

    n events median 0.95LCL 0.95UCL
1 137     83    422     268      NA
2 137     83     NA     625      NA
3 137     83    268     162     467</code></pre>
</div>
</div>
<div class="cell" data-hash="proportional-hazards-models_cache/html/unnamed-chunk-12_8c2f01a7c3c8437c3efb148817c1811f">
<details><summary>Code</summary><div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">bmt.cox</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/survival/man/survfit.html">survfit</a></span><span class="op">(</span>newdata <span class="op">=</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>group <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">bmt</span><span class="op">$</span><span class="va">group</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = bmt.cox, newdata = tibble(group = unique(bmt$group)))

 time n.risk n.event survival1 survival2 survival3
    1    137       1    0.9926    0.9958    0.9891
    2    136       1    0.9852    0.9916    0.9783
   10    135       1    0.9777    0.9874    0.9675
   16    134       1    0.9703    0.9832    0.9568
   32    133       1    0.9629    0.9789    0.9460
   35    132       1    0.9554    0.9746    0.9353
   47    131       2    0.9405    0.9661    0.9139
   48    129       2    0.9255    0.9574    0.8927
   53    127       1    0.9180    0.9530    0.8821
   55    126       1    0.9106    0.9486    0.8715
   63    125       1    0.9031    0.9442    0.8611
   64    124       1    0.8956    0.9398    0.8506
   74    123       2    0.8805    0.9308    0.8297
   76    121       1    0.8730    0.9263    0.8193
   79    120       1    0.8654    0.9218    0.8088
   80    119       2    0.8502    0.9127    0.7882
   84    117       1    0.8427    0.9081    0.7779
   86    116       1    0.8351    0.9035    0.7676
   93    115       1    0.8275    0.8988    0.7574
  100    114       1    0.8199    0.8942    0.7472
  104    113       1    0.8122    0.8895    0.7370
  105    112       2    0.7969    0.8800    0.7167
  107    110       1    0.7892    0.8752    0.7066
  109    109       1    0.7815    0.8704    0.6965
  110    108       1    0.7739    0.8656    0.6865
  113    107       1    0.7662    0.8607    0.6766
  115    106       1    0.7585    0.8559    0.6666
  120    105       1    0.7508    0.8509    0.6567
  122    104       2    0.7352    0.8410    0.6368
  129    102       1    0.7275    0.8359    0.6270
  157    101       1    0.7197    0.8309    0.6172
  162    100       1    0.7119    0.8258    0.6074
  164     99       1    0.7040    0.8207    0.5975
  168     98       1    0.6961    0.8155    0.5877
  172     97       1    0.6882    0.8102    0.5779
  183     96       1    0.6803    0.8050    0.5682
  192     95       1    0.6723    0.7996    0.5584
  194     94       1    0.6643    0.7943    0.5487
  211     93       1    0.6563    0.7889    0.5391
  219     92       1    0.6484    0.7835    0.5295
  230     90       1    0.6404    0.7780    0.5200
  242     89       1    0.6324    0.7726    0.5105
  248     88       1    0.6244    0.7670    0.5010
  268     87       1    0.6164    0.7615    0.4916
  272     86       1    0.6083    0.7558    0.4822
  273     85       1    0.6003    0.7502    0.4730
  276     84       1    0.5923    0.7446    0.4637
  288     83       1    0.5842    0.7388    0.4545
  318     82       1    0.5762    0.7331    0.4454
  332     81       1    0.5682    0.7273    0.4363
  363     80       1    0.5601    0.7215    0.4272
  381     79       1    0.5520    0.7156    0.4182
  383     78       1    0.5440    0.7097    0.4093
  390     77       2    0.5279    0.6978    0.3916
  414     75       1    0.5198    0.6918    0.3829
  418     74       1    0.5118    0.6858    0.3742
  421     73       1    0.5038    0.6797    0.3657
  422     72       1    0.4958    0.6736    0.3573
  456     71       1    0.4878    0.6675    0.3488
  466     70       1    0.4798    0.6612    0.3404
  467     69       1    0.4717    0.6550    0.3320
  481     68       1    0.4636    0.6486    0.3236
  486     67       1    0.4555    0.6422    0.3154
  487     66       1    0.4475    0.6358    0.3073
  526     65       1    0.4395    0.6294    0.2993
  606     63       1    0.4313    0.6228    0.2911
  609     62       1    0.4232    0.6161    0.2832
  625     61       1    0.4151    0.6095    0.2753
  641     60       1    0.4069    0.6027    0.2673
  662     59       1    0.3988    0.5959    0.2596
  677     58       1    0.3907    0.5891    0.2519
  704     57       1    0.3826    0.5821    0.2442
  748     56       1    0.3745    0.5751    0.2366
 1063     47       1    0.3653    0.5671    0.2282
 1074     46       1    0.3562    0.5592    0.2199
 2204      9       1    0.3133    0.5201    0.1821</code></pre>
</div>
</div>
</section></section><section id="adjustment-for-ties-optional" class="level2" data-number="6.3"><h2 data-number="6.3" class="anchored" data-anchor-id="adjustment-for-ties-optional">
<span class="header-section-number">6.3</span> Adjustment for Ties (optional)</h2>
<section id="section" class="level3" data-number="6.3.1"><h3 data-number="6.3.1" class="anchored" data-anchor-id="section">
<span class="header-section-number">6.3.1</span> </h3>
<p>At each time <span class="math inline">\(t_i\)</span> at which more than one of the subjects has an event, let <span class="math inline">\(d_i\)</span> be the number of events at that time, <span class="math inline">\(D_i\)</span> the set of subjects with events at that time, and let <span class="math inline">\(s_i\)</span> be a covariate vector for an artificial subject obtained by adding up the covariate values for the subjects with an event at time <span class="math inline">\(t_i\)</span>. Let <span class="math display">\[\bar\eta_i = \beta_1s_{i1}+\cdots+\beta_ps_{ip}\]</span> and <span class="math inline">\(\bar\theta_i = \text{exp}\left\{\bar\eta_i\right\}\)</span>.</p>
<p>Let <span class="math inline">\(s_i\)</span> be a covariate vector for an artificial subject obtained by adding up the covariate values for the subjects with an event at time <span class="math inline">\(t_i\)</span>. Note that</p>
<p><span class="math display">\[
\begin{aligned}
\bar\eta_i &amp;=\sum_{j \in D_i}\beta_1x_{j1}+\cdots+\beta_px_{jp}\\
&amp;= \beta_1s_{i1}+\cdots+\beta_ps_{ip}\\
\bar\theta_i &amp;= \text{exp}\left\{\bar\eta_i\right\}\\
&amp;= \prod_{j \in D_i}\theta_i
\end{aligned}
\]</span></p>
<section id="breslows-method-for-ties" class="level4"><h4 class="anchored" data-anchor-id="breslows-method-for-ties">Breslow’s method for ties</h4>
<p>Breslow’s method estimates the partial likelihood as</p>
<p><span class="math display">\[
\begin{aligned}
L(\beta|T) &amp;=
\prod_i \frac{\bar\theta_i}{[\sum_{k \in R(t_i)} \theta_k]^{d_i}}\\
&amp;= \prod_i \prod_{j \in D_i}\frac{\theta_j}{\sum_{k \in R(t_i)} \theta_k}
\end{aligned}
\]</span></p>
<p>This method is equivalent to treating each event as distinct and using the non-ties formula. It works best when the number of ties is small. It is the default in many statistical packages, including PROC PHREG in SAS.</p>
</section><section id="efrons-method-for-ties" class="level4"><h4 class="anchored" data-anchor-id="efrons-method-for-ties">Efron’s method for ties</h4>
<p>The other common method is Efron’s, which is the default in R.</p>
<p><span class="math display">\[L(\beta|T)=
\prod_i \frac{\bar\theta_i}{\prod_{j=1}^{d_i}[\sum_{k \in R(t_i)} \theta_k-\frac{j-1}{d_i}\sum_{k \in D_i} \theta_k]}\]</span> This is closer to the exact discrete partial likelihood when there are many ties.</p>
<p>The third option in R (and an option also in SAS as <code>discrete</code>) is the “exact” method, which is the same one used for matched logistic regression.</p>
</section><section id="example-breslows-method" class="level4"><h4 class="anchored" data-anchor-id="example-breslows-method">Example: Breslow’s method</h4>
<p>Suppose as an example we have a time <span class="math inline">\(t\)</span> where there are 20 individuals at risk and three failures. Let the three individuals have risk parameters <span class="math inline">\(\theta_1, \theta_2, \theta_3\)</span> and let the sum of the risk parameters of the remaining 17 individuals be <span class="math inline">\(\theta_R\)</span>. Then the factor in the partial likelihood at time <span class="math inline">\(t\)</span> using Breslow’s method is</p>
<div class="smaller">
<p><span class="math display">\[
\left(\frac{\theta_1}{\theta_R+\theta_1+\theta_2+\theta_3}\right)
\left(\frac{\theta_2}{\theta_R+\theta_1+\theta_2+\theta_3}\right)
\left(\frac{\theta_3}{\theta_R+\theta_1+\theta_2+\theta_3}\right)
\]</span></p>
</div>
<p>If on the other hand, they had died in the order 1,2, 3, then the contribution to the partial likelihood would be:</p>
<div class="smaller">
<p><span class="math display">\[
\left(\frac{\theta_1}{\theta_R+\theta_1+\theta_2+\theta_3}\right)
\left(\frac{\theta_2}{\theta_R+\theta_2+\theta_3}\right)
\left(\frac{\theta_3}{\theta_R+\theta_3}\right)
\]</span></p>
</div>
<p>as the risk set got smaller with each failure. The exact method roughly averages the results for the six possible orderings of the failures.</p>
</section><section id="example-efrons-method" class="level4"><h4 class="anchored" data-anchor-id="example-efrons-method">Example: Efron’s method</h4>
<p>But we don’t know the order they failed in, so instead of reducing the denominator by one risk coefficient each time, we reduce it by the same fraction. This is Efron’s method.</p>
<div class="smaller">
<p><span class="math display">\[\left(\frac{\theta_1}{\theta_R+\theta_1+\theta_2+\theta_3}\right)
\left(\frac{\theta_2}{\theta_R+2(\theta_1+\theta_2+\theta_3)/3}\right)
\left(\frac{\theta_3}{\theta_R+(\theta_1+\theta_2+\theta_3)/3}\right)\]</span></p>
</div>


<!-- -->

</section></section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./intro-to-survival-analysis.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Introduction to Survival Analysis</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./coxph-model-building.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Building Cox Proportional Hazards models</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb21" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Proportional Hazards Models"</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>{{&lt; include shared-config.qmd &gt;}}</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>::: {.content-hidden when-format="revealjs"}</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="fu">## Configuring R {.unnumbered}</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>Functions from these packages will be used throughout this document:</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="in">```{r packages, message = FALSE}</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pander) <span class="co"># format tables for markdown</span></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) <span class="co"># graphics</span></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggeasy) <span class="co"># help with graphics</span></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr) <span class="co"># manipulate data</span></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven) <span class="co"># import Stata files</span></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr) <span class="co"># format R output for markdown</span></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr) <span class="co"># Tools to help to create tidy data</span></span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly) <span class="co"># interactive graphics</span></span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dobson) <span class="co"># datasets from Dobson and Barnett 2018</span></span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(parameters) <span class="co"># format model output tables for markdown</span></span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(conflicted) <span class="co"># check for conflicting function definitions</span></span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a><span class="fu">conflicts_prefer</span>(dplyr<span class="sc">::</span>filter)</span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>Here are some R settings I use in this document:</span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a><span class="in">```{r options, message=FALSE}</span></span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>()) <span class="co"># delete any data that's already loaded into R</span></span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">message =</span> <span class="cn">FALSE</span>)</span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a>pander<span class="sc">::</span><span class="fu">panderOptions</span>(<span class="st">"table.emphasize.rownames"</span>, <span class="cn">FALSE</span>)</span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="st">'digits'</span> <span class="ot">=</span> <span class="dv">4</span>)</span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-35"><a href="#cb21-35" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb21-36"><a href="#cb21-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-37"><a href="#cb21-37" aria-hidden="true" tabindex="-1"></a><span class="fu"># The proportional hazards model</span></span>
<span id="cb21-38"><a href="#cb21-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-39"><a href="#cb21-39" aria-hidden="true" tabindex="-1"></a><span class="fu">## Background on the Proportional Hazards Model</span></span>
<span id="cb21-40"><a href="#cb21-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-41"><a href="#cb21-41" aria-hidden="true" tabindex="-1"></a>The exponential distribution has constant hazard:</span>
<span id="cb21-42"><a href="#cb21-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-43"><a href="#cb21-43" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-44"><a href="#cb21-44" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb21-45"><a href="#cb21-45" aria-hidden="true" tabindex="-1"></a>f(t) &amp;= \lambda e^{-\lambda t}<span class="sc">\\</span></span>
<span id="cb21-46"><a href="#cb21-46" aria-hidden="true" tabindex="-1"></a>S(t) &amp;= e^{-\lambda t}<span class="sc">\\</span></span>
<span id="cb21-47"><a href="#cb21-47" aria-hidden="true" tabindex="-1"></a>h(t) &amp;= \lambda</span>
<span id="cb21-48"><a href="#cb21-48" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb21-49"><a href="#cb21-49" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-50"><a href="#cb21-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-51"><a href="#cb21-51" aria-hidden="true" tabindex="-1"></a>Let's make two generalizations. First, we let the hazard depend on some</span>
<span id="cb21-52"><a href="#cb21-52" aria-hidden="true" tabindex="-1"></a>covariates $x_1,x_2, \dots, x_p$; we will indicate this dependence by extending our notation for hazard:</span>
<span id="cb21-53"><a href="#cb21-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-54"><a href="#cb21-54" aria-hidden="true" tabindex="-1"></a>$$h(t|\boldsymbol x) \eqdef p(T=t|T\ge t, \boldsymbol X = \boldsymbol x)$$</span>
<span id="cb21-55"><a href="#cb21-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-56"><a href="#cb21-56" aria-hidden="true" tabindex="-1"></a>Second, we let the base hazard depend on $t$, but not on the covariates (for now). We can do this using either parametric or semi-parametric approaches.</span>
<span id="cb21-57"><a href="#cb21-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-58"><a href="#cb21-58" aria-hidden="true" tabindex="-1"></a><span class="fu">## Cox's Proportional Hazards Model</span></span>
<span id="cb21-59"><a href="#cb21-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-60"><a href="#cb21-60" aria-hidden="true" tabindex="-1"></a>The generalization is that the hazard function is </span>
<span id="cb21-61"><a href="#cb21-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-62"><a href="#cb21-62" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-63"><a href="#cb21-63" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb21-64"><a href="#cb21-64" aria-hidden="true" tabindex="-1"></a>h(t|x)&amp;= h_0(t)\theta(x)<span class="sc">\\</span></span>
<span id="cb21-65"><a href="#cb21-65" aria-hidden="true" tabindex="-1"></a>\theta(x) &amp;= \exp{\eta(x)}<span class="sc">\\</span></span>
<span id="cb21-66"><a href="#cb21-66" aria-hidden="true" tabindex="-1"></a>\eta(x) &amp;= x'\beta<span class="sc">\\</span></span>
<span id="cb21-67"><a href="#cb21-67" aria-hidden="true" tabindex="-1"></a>&amp;\eqdef \beta_1x_1+\cdots+\beta_px_p</span>
<span id="cb21-68"><a href="#cb21-68" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb21-69"><a href="#cb21-69" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-70"><a href="#cb21-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-71"><a href="#cb21-71" aria-hidden="true" tabindex="-1"></a>The relationship between $h(t|x)$ and $\eta(x)$ has a log link (that is, $\log{h(t|x)} = \log{h_0(t)} + \eta(x)$), as in a generalized linear model.</span>
<span id="cb21-72"><a href="#cb21-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-73"><a href="#cb21-73" aria-hidden="true" tabindex="-1"></a>This model is **semi-parametric**, because the linear predictor depends on estimated</span>
<span id="cb21-74"><a href="#cb21-74" aria-hidden="true" tabindex="-1"></a>parameters but the base hazard function is unspecified. </span>
<span id="cb21-75"><a href="#cb21-75" aria-hidden="true" tabindex="-1"></a>There is no constant term in $\eta(x)$, because it is absorbed in the base hazard. </span>
<span id="cb21-76"><a href="#cb21-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-77"><a href="#cb21-77" aria-hidden="true" tabindex="-1"></a>Alternatively, we could define $\beta_0(t) = \log{h_0(t)}$, and then $\eta(x,t) = \beta_0(t) + \beta_1x_1+\cdots+\beta_px_p$.</span>
<span id="cb21-78"><a href="#cb21-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-79"><a href="#cb21-79" aria-hidden="true" tabindex="-1"></a>For two different individuals with covariate patterns $\boldsymbol x_1$ and $\boldsymbol x_2$, the ratio of the hazard functions (a.k.a. **hazard ratio**, a.k.a. **relative hazard**) is:</span>
<span id="cb21-80"><a href="#cb21-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-81"><a href="#cb21-81" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-82"><a href="#cb21-82" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb21-83"><a href="#cb21-83" aria-hidden="true" tabindex="-1"></a>\frac{h(t|\boldsymbol x_1)}{h(t|\boldsymbol x_2)}</span>
<span id="cb21-84"><a href="#cb21-84" aria-hidden="true" tabindex="-1"></a>&amp;=\frac{h_0(t)\theta(\boldsymbol x_1)}{h_0(t)\theta(\boldsymbol x_2)}<span class="sc">\\</span></span>
<span id="cb21-85"><a href="#cb21-85" aria-hidden="true" tabindex="-1"></a>&amp;=\frac{\theta(\boldsymbol x_1)}{\theta(\boldsymbol x_2)}<span class="sc">\\</span></span>
<span id="cb21-86"><a href="#cb21-86" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb21-87"><a href="#cb21-87" aria-hidden="true" tabindex="-1"></a>$$ </span>
<span id="cb21-88"><a href="#cb21-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-89"><a href="#cb21-89" aria-hidden="true" tabindex="-1"></a>Under the proportional hazards model, this ratio (a.k.a. proportion) does not depend on $t$. This property is a structural limitation of the model; it is called the **proportional hazards assumption**.</span>
<span id="cb21-90"><a href="#cb21-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-91"><a href="#cb21-91" aria-hidden="true" tabindex="-1"></a>::: {#def-pha}</span>
<span id="cb21-92"><a href="#cb21-92" aria-hidden="true" tabindex="-1"></a><span class="fu">## proportional hazards</span></span>
<span id="cb21-93"><a href="#cb21-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-94"><a href="#cb21-94" aria-hidden="true" tabindex="-1"></a>A conditional probability distribution $p(T|X)$ has **proportional hazards** if the hazard ratio $h(t|\boldsymbol x_1)/h(t|\boldsymbol x_2)$ does not depend on $t$. Mathematically, it can be written as:</span>
<span id="cb21-95"><a href="#cb21-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-96"><a href="#cb21-96" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-97"><a href="#cb21-97" aria-hidden="true" tabindex="-1"></a>\frac{h(t|\boldsymbol x_1)}{h(t|\boldsymbol x_2)}</span>
<span id="cb21-98"><a href="#cb21-98" aria-hidden="true" tabindex="-1"></a>= \theta(\boldsymbol x_1,\boldsymbol x_2)</span>
<span id="cb21-99"><a href="#cb21-99" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-100"><a href="#cb21-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-101"><a href="#cb21-101" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb21-102"><a href="#cb21-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-103"><a href="#cb21-103" aria-hidden="true" tabindex="-1"></a>As we saw above, Cox's proportional hazards model has this property, with $\theta(\boldsymbol x_1,\boldsymbol x_2) = \frac{\theta(\boldsymbol x_1)}{\theta(\boldsymbol x_2)}$.</span>
<span id="cb21-104"><a href="#cb21-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-105"><a href="#cb21-105" aria-hidden="true" tabindex="-1"></a>:::{.callout-note}</span>
<span id="cb21-106"><a href="#cb21-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-107"><a href="#cb21-107" aria-hidden="true" tabindex="-1"></a>We are using two similar notations, $\theta(\boldsymbol x_1,\boldsymbol x_2)$ and $\theta(\boldsymbol x)$. We can link these notations if we define $\theta(\boldsymbol x) \eqdef \theta(\boldsymbol x, \boldsymbol 0)$ and $\theta(\boldsymbol 0) = 1$.</span>
<span id="cb21-108"><a href="#cb21-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-109"><a href="#cb21-109" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb21-110"><a href="#cb21-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-111"><a href="#cb21-111" aria-hidden="true" tabindex="-1"></a>It also has additional notable properties:</span>
<span id="cb21-112"><a href="#cb21-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-113"><a href="#cb21-113" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-114"><a href="#cb21-114" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb21-115"><a href="#cb21-115" aria-hidden="true" tabindex="-1"></a>\frac{h(t|\boldsymbol x_1)}{h(t|\boldsymbol x_2)}</span>
<span id="cb21-116"><a href="#cb21-116" aria-hidden="true" tabindex="-1"></a>&amp;=\frac{\theta(\boldsymbol x_1)}{\theta(\boldsymbol x_2)}<span class="sc">\\</span></span>
<span id="cb21-117"><a href="#cb21-117" aria-hidden="true" tabindex="-1"></a>&amp;=\frac{\exp{\eta(\boldsymbol x_1)}}{\exp{\eta(\boldsymbol x_2)}}<span class="sc">\\</span></span>
<span id="cb21-118"><a href="#cb21-118" aria-hidden="true" tabindex="-1"></a>&amp;=\exp{\eta(\boldsymbol x_1)-\eta(\boldsymbol x_2)}<span class="sc">\\</span></span>
<span id="cb21-119"><a href="#cb21-119" aria-hidden="true" tabindex="-1"></a>&amp;=\exp{\boldsymbol x_1'\beta-\boldsymbol x_2'\beta}<span class="sc">\\</span></span>
<span id="cb21-120"><a href="#cb21-120" aria-hidden="true" tabindex="-1"></a>&amp;=\exp{(\boldsymbol x_1 - \boldsymbol x_2)'\beta}<span class="sc">\\</span></span>
<span id="cb21-121"><a href="#cb21-121" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb21-122"><a href="#cb21-122" aria-hidden="true" tabindex="-1"></a>$$ </span>
<span id="cb21-123"><a href="#cb21-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-124"><a href="#cb21-124" aria-hidden="true" tabindex="-1"></a>Hence on the log scale, we have:</span>
<span id="cb21-125"><a href="#cb21-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-126"><a href="#cb21-126" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-127"><a href="#cb21-127" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb21-128"><a href="#cb21-128" aria-hidden="true" tabindex="-1"></a>\log{\frac{h(t|\boldsymbol x_1)}{h(t|\boldsymbol x_2)}}</span>
<span id="cb21-129"><a href="#cb21-129" aria-hidden="true" tabindex="-1"></a>&amp;=\eta(\boldsymbol x_1)-\eta(\boldsymbol x_2)<span class="sc">\\</span></span>
<span id="cb21-130"><a href="#cb21-130" aria-hidden="true" tabindex="-1"></a>&amp;= \boldsymbol x_1'\beta-\boldsymbol x_2'\beta<span class="sc">\\</span></span>
<span id="cb21-131"><a href="#cb21-131" aria-hidden="true" tabindex="-1"></a>&amp;= (\boldsymbol x_1 - \boldsymbol x_2)'\beta</span>
<span id="cb21-132"><a href="#cb21-132" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb21-133"><a href="#cb21-133" aria-hidden="true" tabindex="-1"></a>$$ </span>
<span id="cb21-134"><a href="#cb21-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-135"><a href="#cb21-135" aria-hidden="true" tabindex="-1"></a>If only one covariate $x_j$ is changing, then:</span>
<span id="cb21-136"><a href="#cb21-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-137"><a href="#cb21-137" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-138"><a href="#cb21-138" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb21-139"><a href="#cb21-139" aria-hidden="true" tabindex="-1"></a>\log{\frac{h(t|\boldsymbol x_1)}{h(t|\boldsymbol x_2)}} </span>
<span id="cb21-140"><a href="#cb21-140" aria-hidden="true" tabindex="-1"></a>&amp;=  (x_{1j} - x_{2j}) \cdot \beta_j<span class="sc">\\</span></span>
<span id="cb21-141"><a href="#cb21-141" aria-hidden="true" tabindex="-1"></a>&amp;\propto (x_{1j} - x_{2j})</span>
<span id="cb21-142"><a href="#cb21-142" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb21-143"><a href="#cb21-143" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-144"><a href="#cb21-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-145"><a href="#cb21-145" aria-hidden="true" tabindex="-1"></a>That is, under Cox's model $h(t|\boldsymbol x) = h_0(t)\exp{\boldsymbol x'\beta}$, the log of the hazard ratio is proportional to the difference in $x_j$, with the proportionality coefficient equal to $\beta_j$.</span>
<span id="cb21-146"><a href="#cb21-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-147"><a href="#cb21-147" aria-hidden="true" tabindex="-1"></a>Further,</span>
<span id="cb21-148"><a href="#cb21-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-149"><a href="#cb21-149" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-150"><a href="#cb21-150" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb21-151"><a href="#cb21-151" aria-hidden="true" tabindex="-1"></a>\log{h(t|\boldsymbol x)}</span>
<span id="cb21-152"><a href="#cb21-152" aria-hidden="true" tabindex="-1"></a>&amp;=\log{h_0(t)}  + x'\beta</span>
<span id="cb21-153"><a href="#cb21-153" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb21-154"><a href="#cb21-154" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-155"><a href="#cb21-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-156"><a href="#cb21-156" aria-hidden="true" tabindex="-1"></a>That is, the covariate effects are additive on the log-hazard scale.</span>
<span id="cb21-157"><a href="#cb21-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-158"><a href="#cb21-158" aria-hidden="true" tabindex="-1"></a>See also: </span>
<span id="cb21-159"><a href="#cb21-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-160"><a href="#cb21-160" aria-hidden="true" tabindex="-1"></a><span class="ot">&lt;https://en.wikipedia.org/wiki/Proportional_hazards_model#Why_it_is_called_%22proportional%22&gt;</span></span>
<span id="cb21-161"><a href="#cb21-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-162"><a href="#cb21-162" aria-hidden="true" tabindex="-1"></a><span class="fu">## Additional properties of the proportional hazards model</span></span>
<span id="cb21-163"><a href="#cb21-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-164"><a href="#cb21-164" aria-hidden="true" tabindex="-1"></a>If $h(t|x)= h_0(t)\theta(x)$, then:</span>
<span id="cb21-165"><a href="#cb21-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-166"><a href="#cb21-166" aria-hidden="true" tabindex="-1"></a><span class="fu">### Cumulative hazards are also proportional to $H_0(t)$</span></span>
<span id="cb21-167"><a href="#cb21-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-168"><a href="#cb21-168" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-169"><a href="#cb21-169" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb21-170"><a href="#cb21-170" aria-hidden="true" tabindex="-1"></a>H(t|x)</span>
<span id="cb21-171"><a href="#cb21-171" aria-hidden="true" tabindex="-1"></a>&amp;\eqdef \int_{u=0}^t h(u)du<span class="sc">\\</span></span>
<span id="cb21-172"><a href="#cb21-172" aria-hidden="true" tabindex="-1"></a>&amp;= \int_{u=0}^t h_0(u)\theta(x)du<span class="sc">\\</span></span>
<span id="cb21-173"><a href="#cb21-173" aria-hidden="true" tabindex="-1"></a>&amp;= \theta(x)\int_{u=0}^t h_0(u)du<span class="sc">\\</span></span>
<span id="cb21-174"><a href="#cb21-174" aria-hidden="true" tabindex="-1"></a>&amp;= \theta(x)H_0(t)</span>
<span id="cb21-175"><a href="#cb21-175" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb21-176"><a href="#cb21-176" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-177"><a href="#cb21-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-178"><a href="#cb21-178" aria-hidden="true" tabindex="-1"></a>where $H_0(t) \eqdef H(t|0) = \int_{u=0}^t h_0(u)du$.</span>
<span id="cb21-179"><a href="#cb21-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-180"><a href="#cb21-180" aria-hidden="true" tabindex="-1"></a><span class="fu">### Survival functions are exponential multiples of $S_0(t)$</span></span>
<span id="cb21-181"><a href="#cb21-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-182"><a href="#cb21-182" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-183"><a href="#cb21-183" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb21-184"><a href="#cb21-184" aria-hidden="true" tabindex="-1"></a>S(t|x)</span>
<span id="cb21-185"><a href="#cb21-185" aria-hidden="true" tabindex="-1"></a>&amp;= \exp{-H(t|x)}<span class="sc">\\</span></span>
<span id="cb21-186"><a href="#cb21-186" aria-hidden="true" tabindex="-1"></a>&amp;= \exp{-\theta(x)\cdot H_0(t)}<span class="sc">\\</span></span>
<span id="cb21-187"><a href="#cb21-187" aria-hidden="true" tabindex="-1"></a>&amp;= \left(\exp{- H_0(t)}\right)^{\theta(x)}<span class="sc">\\</span></span>
<span id="cb21-188"><a href="#cb21-188" aria-hidden="true" tabindex="-1"></a>&amp;= \left(S_0(t)\right)^{\theta(x)}<span class="sc">\\</span></span>
<span id="cb21-189"><a href="#cb21-189" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb21-190"><a href="#cb21-190" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-191"><a href="#cb21-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-192"><a href="#cb21-192" aria-hidden="true" tabindex="-1"></a>where $S_0(t) \eqdef P(T\ge t | \boldsymbol X = 0)$ is the survival function for an individual whose covariates are all equal to their default values.</span>
<span id="cb21-193"><a href="#cb21-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-194"><a href="#cb21-194" aria-hidden="true" tabindex="-1"></a><span class="fu">## Testing the proportional hazards assumption</span></span>
<span id="cb21-195"><a href="#cb21-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-196"><a href="#cb21-196" aria-hidden="true" tabindex="-1"></a>The Nelson-Aalen estimate of the cumulative hazard is usually used for estimates of the hazard and often the cumulative hazard.</span>
<span id="cb21-197"><a href="#cb21-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-198"><a href="#cb21-198" aria-hidden="true" tabindex="-1"></a>If the hazards of the three groups are proportional, that means that the ratio of the hazards is constant over $t$. We can test this using the ratios of the estimated cumulative hazards, which also would be</span>
<span id="cb21-199"><a href="#cb21-199" aria-hidden="true" tabindex="-1"></a>proportional, as shown above.</span>
<span id="cb21-200"><a href="#cb21-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-203"><a href="#cb21-203" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb21-204"><a href="#cb21-204" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(KMsurv)</span>
<span id="cb21-205"><a href="#cb21-205" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb21-206"><a href="#cb21-206" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(bmt)</span>
<span id="cb21-207"><a href="#cb21-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-208"><a href="#cb21-208" aria-hidden="true" tabindex="-1"></a>bmt <span class="ot">=</span> </span>
<span id="cb21-209"><a href="#cb21-209" aria-hidden="true" tabindex="-1"></a>  bmt <span class="sc">|&gt;</span> </span>
<span id="cb21-210"><a href="#cb21-210" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span> </span>
<span id="cb21-211"><a href="#cb21-211" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb21-212"><a href="#cb21-212" aria-hidden="true" tabindex="-1"></a>    <span class="at">group =</span> </span>
<span id="cb21-213"><a href="#cb21-213" aria-hidden="true" tabindex="-1"></a>      group <span class="sc">|&gt;</span> </span>
<span id="cb21-214"><a href="#cb21-214" aria-hidden="true" tabindex="-1"></a>      <span class="fu">factor</span>(</span>
<span id="cb21-215"><a href="#cb21-215" aria-hidden="true" tabindex="-1"></a>        <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"ALL"</span>,<span class="st">"Low Risk AML"</span>,<span class="st">"High Risk AML"</span>)))</span>
<span id="cb21-216"><a href="#cb21-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-217"><a href="#cb21-217" aria-hidden="true" tabindex="-1"></a>nafit <span class="ot">=</span> <span class="fu">survfit</span>(</span>
<span id="cb21-218"><a href="#cb21-218" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> <span class="fu">Surv</span>(t2,d3) <span class="sc">~</span> group,</span>
<span id="cb21-219"><a href="#cb21-219" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"fleming-harrington"</span>,</span>
<span id="cb21-220"><a href="#cb21-220" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> bmt)</span>
<span id="cb21-221"><a href="#cb21-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-222"><a href="#cb21-222" aria-hidden="true" tabindex="-1"></a>bmt_curves <span class="ot">=</span> <span class="fu">tibble</span>(<span class="at">timevec =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>)</span>
<span id="cb21-223"><a href="#cb21-223" aria-hidden="true" tabindex="-1"></a>sf1 <span class="ot">&lt;-</span> <span class="fu">with</span>(nafit[<span class="dv">1</span>], <span class="fu">stepfun</span>(time,<span class="fu">c</span>(<span class="dv">1</span>,surv)))</span>
<span id="cb21-224"><a href="#cb21-224" aria-hidden="true" tabindex="-1"></a>sf2 <span class="ot">&lt;-</span> <span class="fu">with</span>(nafit[<span class="dv">2</span>], <span class="fu">stepfun</span>(time,<span class="fu">c</span>(<span class="dv">1</span>,surv)))</span>
<span id="cb21-225"><a href="#cb21-225" aria-hidden="true" tabindex="-1"></a>sf3 <span class="ot">&lt;-</span> <span class="fu">with</span>(nafit[<span class="dv">3</span>], <span class="fu">stepfun</span>(time,<span class="fu">c</span>(<span class="dv">1</span>,surv)))</span>
<span id="cb21-226"><a href="#cb21-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-227"><a href="#cb21-227" aria-hidden="true" tabindex="-1"></a>bmt_curves <span class="ot">=</span> </span>
<span id="cb21-228"><a href="#cb21-228" aria-hidden="true" tabindex="-1"></a>  bmt_curves <span class="sc">|&gt;</span> </span>
<span id="cb21-229"><a href="#cb21-229" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb21-230"><a href="#cb21-230" aria-hidden="true" tabindex="-1"></a>    <span class="at">cumhaz1 =</span> <span class="sc">-</span><span class="fu">log</span>(<span class="fu">sf1</span>(timevec)),</span>
<span id="cb21-231"><a href="#cb21-231" aria-hidden="true" tabindex="-1"></a>    <span class="at">cumhaz2 =</span> <span class="sc">-</span><span class="fu">log</span>(<span class="fu">sf2</span>(timevec)),</span>
<span id="cb21-232"><a href="#cb21-232" aria-hidden="true" tabindex="-1"></a>    <span class="at">cumhaz3 =</span> <span class="sc">-</span><span class="fu">log</span>(<span class="fu">sf3</span>(timevec)))</span>
<span id="cb21-233"><a href="#cb21-233" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-234"><a href="#cb21-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-237"><a href="#cb21-237" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb21-238"><a href="#cb21-238" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Hazard Ratios by Disease Group"</span></span>
<span id="cb21-239"><a href="#cb21-239" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb21-240"><a href="#cb21-240" aria-hidden="true" tabindex="-1"></a>bmt_rel_hazard_plot <span class="ot">=</span> </span>
<span id="cb21-241"><a href="#cb21-241" aria-hidden="true" tabindex="-1"></a>  bmt_curves <span class="sc">|&gt;</span> </span>
<span id="cb21-242"><a href="#cb21-242" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(</span>
<span id="cb21-243"><a href="#cb21-243" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(</span>
<span id="cb21-244"><a href="#cb21-244" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> timevec,</span>
<span id="cb21-245"><a href="#cb21-245" aria-hidden="true" tabindex="-1"></a>      <span class="at">y =</span> cumhaz1<span class="sc">/</span>cumhaz2)</span>
<span id="cb21-246"><a href="#cb21-246" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb21-247"><a href="#cb21-247" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">col =</span> <span class="st">"ALL/Low Risk AML"</span>)) <span class="sc">+</span> </span>
<span id="cb21-248"><a href="#cb21-248" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Hazard Ratio"</span>) <span class="sc">+</span></span>
<span id="cb21-249"><a href="#cb21-249" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Time"</span>) <span class="sc">+</span> </span>
<span id="cb21-250"><a href="#cb21-250" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="dv">6</span>) <span class="sc">+</span></span>
<span id="cb21-251"><a href="#cb21-251" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> cumhaz3<span class="sc">/</span>cumhaz1, <span class="at">col =</span> <span class="st">"High Risk AML/ALL"</span>)) <span class="sc">+</span></span>
<span id="cb21-252"><a href="#cb21-252" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> cumhaz3<span class="sc">/</span>cumhaz2, <span class="at">col =</span> <span class="st">"High Risk AML/Low Risk AML"</span>)) <span class="sc">+</span></span>
<span id="cb21-253"><a href="#cb21-253" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb21-254"><a href="#cb21-254" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">colour =</span> <span class="st">"Comparison"</span>) <span class="sc">+</span></span>
<span id="cb21-255"><a href="#cb21-255" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"bottom"</span>)</span>
<span id="cb21-256"><a href="#cb21-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-257"><a href="#cb21-257" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(bmt_rel_hazard_plot)</span>
<span id="cb21-258"><a href="#cb21-258" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-259"><a href="#cb21-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-260"><a href="#cb21-260" aria-hidden="true" tabindex="-1"></a>We can zoom in on 30-300 days to take a closer look:</span>
<span id="cb21-261"><a href="#cb21-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-264"><a href="#cb21-264" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb21-265"><a href="#cb21-265" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Hazard Ratios by Disease Group (30-300 Days)"</span></span>
<span id="cb21-266"><a href="#cb21-266" aria-hidden="true" tabindex="-1"></a>bmt_rel_hazard_plot <span class="sc">+</span> <span class="fu">xlim</span>(<span class="fu">c</span>(<span class="dv">30</span>,<span class="dv">300</span>))</span>
<span id="cb21-267"><a href="#cb21-267" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-268"><a href="#cb21-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-269"><a href="#cb21-269" aria-hidden="true" tabindex="-1"></a><span class="fu">## Smoothed hazard functions</span></span>
<span id="cb21-270"><a href="#cb21-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-271"><a href="#cb21-271" aria-hidden="true" tabindex="-1"></a>The Nelson-Aalen estimate of the cumulative hazard is usually used for</span>
<span id="cb21-272"><a href="#cb21-272" aria-hidden="true" tabindex="-1"></a>estimates of the hazard. Since the hazard is the derivative of the</span>
<span id="cb21-273"><a href="#cb21-273" aria-hidden="true" tabindex="-1"></a>cumulative hazard, we need a smooth estimate of the cumulative hazard,</span>
<span id="cb21-274"><a href="#cb21-274" aria-hidden="true" tabindex="-1"></a>which is provided by smoothing the step-function cumulative hazard.</span>
<span id="cb21-275"><a href="#cb21-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-276"><a href="#cb21-276" aria-hidden="true" tabindex="-1"></a>The R package <span class="in">`muhaz`</span> handles this for us. What we are looking for is</span>
<span id="cb21-277"><a href="#cb21-277" aria-hidden="true" tabindex="-1"></a>whether the hazard function is more or less the same shape, increasing,</span>
<span id="cb21-278"><a href="#cb21-278" aria-hidden="true" tabindex="-1"></a>decreasing, constant, etc. Are the hazards "proportional"?</span>
<span id="cb21-279"><a href="#cb21-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-282"><a href="#cb21-282" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb21-283"><a href="#cb21-283" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Disease-Free Cumulative Hazard by Disease Group"</span></span>
<span id="cb21-284"><a href="#cb21-284" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb21-285"><a href="#cb21-285" aria-hidden="true" tabindex="-1"></a>  <span class="fu">survfit</span>(<span class="fu">Surv</span>(t2,d3)<span class="sc">~</span>group,<span class="at">data=</span>bmt),</span>
<span id="cb21-286"><a href="#cb21-286" aria-hidden="true" tabindex="-1"></a>  <span class="at">col=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,</span>
<span id="cb21-287"><a href="#cb21-287" aria-hidden="true" tabindex="-1"></a>  <span class="at">lwd=</span><span class="dv">2</span>,</span>
<span id="cb21-288"><a href="#cb21-288" aria-hidden="true" tabindex="-1"></a>  <span class="at">fun=</span><span class="st">"cumhaz"</span>,</span>
<span id="cb21-289"><a href="#cb21-289" aria-hidden="true" tabindex="-1"></a>  <span class="at">mark.time =</span> <span class="cn">TRUE</span>)</span>
<span id="cb21-290"><a href="#cb21-290" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"bottomright"</span>,<span class="fu">c</span>(<span class="st">"ALL"</span>,<span class="st">"Low Risk AML"</span>,<span class="st">"High Risk AML"</span>),<span class="at">col=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,<span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb21-291"><a href="#cb21-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-292"><a href="#cb21-292" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-293"><a href="#cb21-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-296"><a href="#cb21-296" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb21-297"><a href="#cb21-297" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Smoothed Hazard Rate Estimates by Disease Group"</span></span>
<span id="cb21-298"><a href="#cb21-298" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(muhaz)</span>
<span id="cb21-299"><a href="#cb21-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-300"><a href="#cb21-300" aria-hidden="true" tabindex="-1"></a><span class="fu">muhaz</span>(bmt<span class="sc">$</span>t2,bmt<span class="sc">$</span>d3,bmt<span class="sc">$</span>group<span class="sc">==</span><span class="st">"High Risk AML"</span>) <span class="sc">|&gt;</span> <span class="fu">plot</span>(<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">3</span>)</span>
<span id="cb21-301"><a href="#cb21-301" aria-hidden="true" tabindex="-1"></a><span class="fu">muhaz</span>(bmt<span class="sc">$</span>t2,bmt<span class="sc">$</span>d3,bmt<span class="sc">$</span>group<span class="sc">==</span><span class="st">"ALL"</span>) <span class="sc">|&gt;</span> <span class="fu">lines</span>(<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">1</span>)</span>
<span id="cb21-302"><a href="#cb21-302" aria-hidden="true" tabindex="-1"></a><span class="fu">muhaz</span>(bmt<span class="sc">$</span>t2,bmt<span class="sc">$</span>d3,bmt<span class="sc">$</span>group<span class="sc">==</span><span class="st">"Low Risk AML"</span>) <span class="sc">|&gt;</span> <span class="fu">lines</span>(<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb21-303"><a href="#cb21-303" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>,<span class="fu">c</span>(<span class="st">"ALL"</span>,<span class="st">"Low Risk AML"</span>,<span class="st">"High Risk AML"</span>),<span class="at">col=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,<span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb21-304"><a href="#cb21-304" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-305"><a href="#cb21-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-306"><a href="#cb21-306" aria-hidden="true" tabindex="-1"></a>Group 3 was plotted first because it has the highest hazard.</span>
<span id="cb21-307"><a href="#cb21-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-308"><a href="#cb21-308" aria-hidden="true" tabindex="-1"></a>We will see that except for an initial blip in the high risk AML group,</span>
<span id="cb21-309"><a href="#cb21-309" aria-hidden="true" tabindex="-1"></a>the hazards look roughly proportional . They are all strongly</span>
<span id="cb21-310"><a href="#cb21-310" aria-hidden="true" tabindex="-1"></a>decreasing.</span>
<span id="cb21-311"><a href="#cb21-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-312"><a href="#cb21-312" aria-hidden="true" tabindex="-1"></a><span class="fu">## Fitting the Proportional Hazards Model</span></span>
<span id="cb21-313"><a href="#cb21-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-314"><a href="#cb21-314" aria-hidden="true" tabindex="-1"></a>How do we fit a proportional hazards regression model? We need to</span>
<span id="cb21-315"><a href="#cb21-315" aria-hidden="true" tabindex="-1"></a>estimate the coefficients of the covariates, and we need to estimate the</span>
<span id="cb21-316"><a href="#cb21-316" aria-hidden="true" tabindex="-1"></a>base hazard $h_0(t)$. For the covariates, supposing for simplicity that</span>
<span id="cb21-317"><a href="#cb21-317" aria-hidden="true" tabindex="-1"></a>there are no tied event times, let the event times for the whole data</span>
<span id="cb21-318"><a href="#cb21-318" aria-hidden="true" tabindex="-1"></a>set be $t_1, t_2,\ldots,t_D$. Let the risk set at time $t_i$ be $R(t_i)$</span>
<span id="cb21-319"><a href="#cb21-319" aria-hidden="true" tabindex="-1"></a>and </span>
<span id="cb21-320"><a href="#cb21-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-321"><a href="#cb21-321" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-322"><a href="#cb21-322" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb21-323"><a href="#cb21-323" aria-hidden="true" tabindex="-1"></a>\eta(\boldsymbol{x}) &amp;= \beta_1x_{1}+\cdots+\beta_p x_{p}<span class="sc">\\</span></span>
<span id="cb21-324"><a href="#cb21-324" aria-hidden="true" tabindex="-1"></a>\theta(\boldsymbol{x}) &amp;= e^{\eta(\boldsymbol{x})}<span class="sc">\\</span></span>
<span id="cb21-325"><a href="#cb21-325" aria-hidden="true" tabindex="-1"></a>h(t|X=x)&amp;= h_0(t)e^{\eta(\boldsymbol{x})}=\theta(\boldsymbol{x}) h_0(t)</span>
<span id="cb21-326"><a href="#cb21-326" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb21-327"><a href="#cb21-327" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-328"><a href="#cb21-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-329"><a href="#cb21-329" aria-hidden="true" tabindex="-1"></a>Conditional on a single failure at time $t$, the probability that the</span>
<span id="cb21-330"><a href="#cb21-330" aria-hidden="true" tabindex="-1"></a>event is due to subject $f\in R(t)$ is approximately</span>
<span id="cb21-331"><a href="#cb21-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-332"><a href="#cb21-332" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-333"><a href="#cb21-333" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb21-334"><a href="#cb21-334" aria-hidden="true" tabindex="-1"></a>\Pr(f \text{ fails}|\text{1 failure at } t) </span>
<span id="cb21-335"><a href="#cb21-335" aria-hidden="true" tabindex="-1"></a>&amp;= \frac{h_0(t)e^{\eta(\boldsymbol{x}_f)}}{\sum_{k \in R(t)}h_0(t)e^{\eta(\boldsymbol{x}_f)}}<span class="sc">\\</span></span>
<span id="cb21-336"><a href="#cb21-336" aria-hidden="true" tabindex="-1"></a>&amp;=\frac{\theta(\boldsymbol{x}_f)}{\sum_{k \in R(t)} \theta(\boldsymbol{x}_k)}</span>
<span id="cb21-337"><a href="#cb21-337" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb21-338"><a href="#cb21-338" aria-hidden="true" tabindex="-1"></a>$$ </span>
<span id="cb21-339"><a href="#cb21-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-340"><a href="#cb21-340" aria-hidden="true" tabindex="-1"></a>The logic behind this has several steps. We first fix (ex post) the</span>
<span id="cb21-341"><a href="#cb21-341" aria-hidden="true" tabindex="-1"></a>failure times and note that in this discrete context, the probability</span>
<span id="cb21-342"><a href="#cb21-342" aria-hidden="true" tabindex="-1"></a>$p_j$ that a subject $j$ in the risk set fails at time $t$ is just the</span>
<span id="cb21-343"><a href="#cb21-343" aria-hidden="true" tabindex="-1"></a>hazard of that subject at that time.</span>
<span id="cb21-344"><a href="#cb21-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-345"><a href="#cb21-345" aria-hidden="true" tabindex="-1"></a>If all of the $p_j$ are small, the chance that exactly one subject fails</span>
<span id="cb21-346"><a href="#cb21-346" aria-hidden="true" tabindex="-1"></a>is</span>
<span id="cb21-347"><a href="#cb21-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-348"><a href="#cb21-348" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-349"><a href="#cb21-349" aria-hidden="true" tabindex="-1"></a>\sum_{k\in R(t)}p_k\left<span class="co">[</span><span class="ot">\prod_{m\in R(t), m\ne k} (1-p_m)\right</span><span class="co">]</span>\approx\sum_{k\in R(t)}p_k</span>
<span id="cb21-350"><a href="#cb21-350" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-351"><a href="#cb21-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-352"><a href="#cb21-352" aria-hidden="true" tabindex="-1"></a>If subject $i$ is the one who experiences the event of interest at time</span>
<span id="cb21-353"><a href="#cb21-353" aria-hidden="true" tabindex="-1"></a>$t_i$, then the **partial likelihood** is</span>
<span id="cb21-354"><a href="#cb21-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-355"><a href="#cb21-355" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-356"><a href="#cb21-356" aria-hidden="true" tabindex="-1"></a>\mathcal L^*(\beta|T)=</span>
<span id="cb21-357"><a href="#cb21-357" aria-hidden="true" tabindex="-1"></a>\prod_i \frac{\theta(x_i)}{\sum_{k \in R(t_i)} \theta(\boldsymbol{x}_k)}</span>
<span id="cb21-358"><a href="#cb21-358" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-359"><a href="#cb21-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-360"><a href="#cb21-360" aria-hidden="true" tabindex="-1"></a>and we can numerically maximize this with respect to the coefficients</span>
<span id="cb21-361"><a href="#cb21-361" aria-hidden="true" tabindex="-1"></a>$\boldsymbol{\beta}$ that specify</span>
<span id="cb21-362"><a href="#cb21-362" aria-hidden="true" tabindex="-1"></a>$\eta(\boldsymbol{x}) = \boldsymbol{x}'\boldsymbol{\beta}$. When there</span>
<span id="cb21-363"><a href="#cb21-363" aria-hidden="true" tabindex="-1"></a>are tied event times adjustments need to be made, but the likelihood is</span>
<span id="cb21-364"><a href="#cb21-364" aria-hidden="true" tabindex="-1"></a>still similar. Note that we don't need to know the base hazard to solve</span>
<span id="cb21-365"><a href="#cb21-365" aria-hidden="true" tabindex="-1"></a>for the coefficients.</span>
<span id="cb21-366"><a href="#cb21-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-367"><a href="#cb21-367" aria-hidden="true" tabindex="-1"></a>Once we have coefficient estimates</span>
<span id="cb21-368"><a href="#cb21-368" aria-hidden="true" tabindex="-1"></a>$\hat{\boldsymbol{\beta}} =(\hat \beta_1,\ldots,\hat\beta_p)$, this also</span>
<span id="cb21-369"><a href="#cb21-369" aria-hidden="true" tabindex="-1"></a>defines $\hat\eta(x)$ and $\hat\theta(x)$ and then the estimated base</span>
<span id="cb21-370"><a href="#cb21-370" aria-hidden="true" tabindex="-1"></a>cumulative hazard function is $$\hat H(t)=</span>
<span id="cb21-371"><a href="#cb21-371" aria-hidden="true" tabindex="-1"></a>\sum_{t_i &lt; t} \frac{d_i}{\sum_{k\in R(t_i)} \theta(x_k)}$$ which</span>
<span id="cb21-372"><a href="#cb21-372" aria-hidden="true" tabindex="-1"></a>reduces to the Nelson-Aalen estimate when there are no covariates. There</span>
<span id="cb21-373"><a href="#cb21-373" aria-hidden="true" tabindex="-1"></a>are numerous other estimates that have been proposed as well.</span>
<span id="cb21-374"><a href="#cb21-374" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-375"><a href="#cb21-375" aria-hidden="true" tabindex="-1"></a><span class="fu"># Cox Model for the `bmt` data</span></span>
<span id="cb21-376"><a href="#cb21-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-377"><a href="#cb21-377" aria-hidden="true" tabindex="-1"></a><span class="fu">## Fit the model</span></span>
<span id="cb21-378"><a href="#cb21-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-381"><a href="#cb21-381" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb21-382"><a href="#cb21-382" aria-hidden="true" tabindex="-1"></a>bmt.cox <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(t2, d3) <span class="sc">~</span> group, <span class="at">data =</span> bmt)</span>
<span id="cb21-383"><a href="#cb21-383" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bmt.cox)</span>
<span id="cb21-384"><a href="#cb21-384" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-385"><a href="#cb21-385" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-386"><a href="#cb21-386" aria-hidden="true" tabindex="-1"></a>The table provides hypothesis tests comparing groups 2 and 3 to group 1.</span>
<span id="cb21-387"><a href="#cb21-387" aria-hidden="true" tabindex="-1"></a>Group 3 has the highest hazard, so the most significant comparison is</span>
<span id="cb21-388"><a href="#cb21-388" aria-hidden="true" tabindex="-1"></a>not directly shown.</span>
<span id="cb21-389"><a href="#cb21-389" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-390"><a href="#cb21-390" aria-hidden="true" tabindex="-1"></a>The coefficient 0.3834 is on the log-hazard-ratio scale, as in</span>
<span id="cb21-391"><a href="#cb21-391" aria-hidden="true" tabindex="-1"></a>log-risk-ratio. The next column gives the hazard ratio 1.4673, and a</span>
<span id="cb21-392"><a href="#cb21-392" aria-hidden="true" tabindex="-1"></a>hypothesis (Wald) test.</span>
<span id="cb21-393"><a href="#cb21-393" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-394"><a href="#cb21-394" aria-hidden="true" tabindex="-1"></a>The (not shown) group 3 vs. group 2 log hazard ratio is 0.3834 + 0.5742</span>
<span id="cb21-395"><a href="#cb21-395" aria-hidden="true" tabindex="-1"></a>= 0.9576. The hazard ratio is then exp(0.9576) or 2.605.</span>
<span id="cb21-396"><a href="#cb21-396" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-397"><a href="#cb21-397" aria-hidden="true" tabindex="-1"></a>Inference on all coefficients and combinations can be constructed using</span>
<span id="cb21-398"><a href="#cb21-398" aria-hidden="true" tabindex="-1"></a><span class="in">`coef(bmt.cox)`</span> and <span class="in">`vcov(bmt.cox)`</span> as with logistic and poisson</span>
<span id="cb21-399"><a href="#cb21-399" aria-hidden="true" tabindex="-1"></a>regression.</span>
<span id="cb21-400"><a href="#cb21-400" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-401"><a href="#cb21-401" aria-hidden="true" tabindex="-1"></a>**Concordance** is agreement of first failure between pairs of subjects</span>
<span id="cb21-402"><a href="#cb21-402" aria-hidden="true" tabindex="-1"></a>and higher predicted risk between those subjects, omitting</span>
<span id="cb21-403"><a href="#cb21-403" aria-hidden="true" tabindex="-1"></a>non-informative pairs.</span>
<span id="cb21-404"><a href="#cb21-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-405"><a href="#cb21-405" aria-hidden="true" tabindex="-1"></a>The Rsquare value is Cox and Snell's pseudo R-squared and is not very</span>
<span id="cb21-406"><a href="#cb21-406" aria-hidden="true" tabindex="-1"></a>useful.</span>
<span id="cb21-407"><a href="#cb21-407" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-408"><a href="#cb21-408" aria-hidden="true" tabindex="-1"></a><span class="in">`summary()`</span> prints three tests for whether the model with the group</span>
<span id="cb21-409"><a href="#cb21-409" aria-hidden="true" tabindex="-1"></a>covariate is better than the one without</span>
<span id="cb21-410"><a href="#cb21-410" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-411"><a href="#cb21-411" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`Likelihood ratio test`</span> (chi-squared)</span>
<span id="cb21-412"><a href="#cb21-412" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`Wald test`</span> (also chi-squared), obtained by adding the squares of the z-scores</span>
<span id="cb21-413"><a href="#cb21-413" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`Score`</span> = log-rank test, as with comparison of survival functions.</span>
<span id="cb21-414"><a href="#cb21-414" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-415"><a href="#cb21-415" aria-hidden="true" tabindex="-1"></a>The likelihood ratio test is probably best in smaller samples, followed</span>
<span id="cb21-416"><a href="#cb21-416" aria-hidden="true" tabindex="-1"></a>by the Wald test.</span>
<span id="cb21-417"><a href="#cb21-417" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-418"><a href="#cb21-418" aria-hidden="true" tabindex="-1"></a><span class="fu">## Survival Curves from the Cox Model</span></span>
<span id="cb21-419"><a href="#cb21-419" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-420"><a href="#cb21-420" aria-hidden="true" tabindex="-1"></a>We can take a look at the resulting group-specific curves:</span>
<span id="cb21-421"><a href="#cb21-421" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-424"><a href="#cb21-424" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb21-425"><a href="#cb21-425" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Survival Functions for Three Groups by KM and Cox Model"</span></span>
<span id="cb21-426"><a href="#cb21-426" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-427"><a href="#cb21-427" aria-hidden="true" tabindex="-1"></a>km_fit <span class="ot">=</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(t2, d3) <span class="sc">~</span> group, <span class="at">data =</span> <span class="fu">as.data.frame</span>(bmt))</span>
<span id="cb21-428"><a href="#cb21-428" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-429"><a href="#cb21-429" aria-hidden="true" tabindex="-1"></a>cox_fit <span class="ot">=</span> <span class="fu">survfit</span>(</span>
<span id="cb21-430"><a href="#cb21-430" aria-hidden="true" tabindex="-1"></a>  bmt.cox, </span>
<span id="cb21-431"><a href="#cb21-431" aria-hidden="true" tabindex="-1"></a>  <span class="at">newdata =</span> </span>
<span id="cb21-432"><a href="#cb21-432" aria-hidden="true" tabindex="-1"></a>    <span class="fu">data.frame</span>(</span>
<span id="cb21-433"><a href="#cb21-433" aria-hidden="true" tabindex="-1"></a>      <span class="at">group =</span> <span class="fu">unique</span>(bmt<span class="sc">$</span>group), </span>
<span id="cb21-434"><a href="#cb21-434" aria-hidden="true" tabindex="-1"></a>      <span class="at">row.names =</span> <span class="fu">unique</span>(bmt<span class="sc">$</span>group)))</span>
<span id="cb21-435"><a href="#cb21-435" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-436"><a href="#cb21-436" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survminer)</span>
<span id="cb21-437"><a href="#cb21-437" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-438"><a href="#cb21-438" aria-hidden="true" tabindex="-1"></a><span class="fu">list</span>(<span class="at">KM =</span> km_fit, <span class="at">Cox =</span> cox_fit) <span class="sc">|&gt;</span> </span>
<span id="cb21-439"><a href="#cb21-439" aria-hidden="true" tabindex="-1"></a>  survminer<span class="sc">::</span><span class="fu">ggsurvplot</span>(</span>
<span id="cb21-440"><a href="#cb21-440" aria-hidden="true" tabindex="-1"></a>    <span class="co"># facet.by = "group",</span></span>
<span id="cb21-441"><a href="#cb21-441" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend =</span> <span class="st">"bottom"</span>, </span>
<span id="cb21-442"><a href="#cb21-442" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.title =</span> <span class="st">""</span>,</span>
<span id="cb21-443"><a href="#cb21-443" aria-hidden="true" tabindex="-1"></a>    <span class="at">combine =</span> <span class="cn">TRUE</span>, </span>
<span id="cb21-444"><a href="#cb21-444" aria-hidden="true" tabindex="-1"></a>    <span class="at">fun =</span> <span class="st">'pct'</span>, </span>
<span id="cb21-445"><a href="#cb21-445" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> .<span class="dv">5</span>,</span>
<span id="cb21-446"><a href="#cb21-446" aria-hidden="true" tabindex="-1"></a>    <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>(), </span>
<span id="cb21-447"><a href="#cb21-447" aria-hidden="true" tabindex="-1"></a>    <span class="at">conf.int =</span> <span class="cn">FALSE</span>, </span>
<span id="cb21-448"><a href="#cb21-448" aria-hidden="true" tabindex="-1"></a>    <span class="at">censor =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb21-449"><a href="#cb21-449" aria-hidden="true" tabindex="-1"></a>  <span class="fu">suppressWarnings</span>() <span class="co"># ggsurvplot() throws some warnings that aren't too worrying</span></span>
<span id="cb21-450"><a href="#cb21-450" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-451"><a href="#cb21-451" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-452"><a href="#cb21-452" aria-hidden="true" tabindex="-1"></a>When we use <span class="in">`survfit()`</span> with a Cox model, we have to specify the covariate levels we are interested in; the argument <span class="in">`newdata`</span> should include a <span class="in">`data.frame`</span> with the same named columns as the predictors in the Cox model and one or more levels of each.</span>
<span id="cb21-453"><a href="#cb21-453" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-454"><a href="#cb21-454" aria-hidden="true" tabindex="-1"></a>Otherwise (that is, if the <span class="in">`newdata`</span> argument is missing), a curve is produced for a single "pseudo" subject with covariate values equal to the means component of the fit. </span>
<span id="cb21-455"><a href="#cb21-455" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-456"><a href="#cb21-456" aria-hidden="true" tabindex="-1"></a>The resulting curve(s) almost never make sense, but the default remains due to an unwarranted attachment to the</span>
<span id="cb21-457"><a href="#cb21-457" aria-hidden="true" tabindex="-1"></a>option shown by some users and by other packages.</span>
<span id="cb21-458"><a href="#cb21-458" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-459"><a href="#cb21-459" aria-hidden="true" tabindex="-1"></a>Two particularly egregious examples are factor variables and</span>
<span id="cb21-460"><a href="#cb21-460" aria-hidden="true" tabindex="-1"></a>interactions. Suppose one were studying interspecies transmission of a virus, and the data set has a factor variable with levels ("pig", "chicken") and about equal numbers of observations for each. The "mean" covariate level will be 0.5 -- is this a flying pig?</span>
<span id="cb21-461"><a href="#cb21-461" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-462"><a href="#cb21-462" aria-hidden="true" tabindex="-1"></a><span class="fu">## Examining `survfit`</span></span>
<span id="cb21-463"><a href="#cb21-463" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-466"><a href="#cb21-466" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb21-467"><a href="#cb21-467" aria-hidden="true" tabindex="-1"></a><span class="fu">survfit</span>(<span class="fu">Surv</span>(t2, d3)<span class="sc">~</span>group,<span class="at">data=</span>bmt)</span>
<span id="cb21-468"><a href="#cb21-468" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-469"><a href="#cb21-469" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-472"><a href="#cb21-472" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb21-473"><a href="#cb21-473" aria-hidden="true" tabindex="-1"></a><span class="fu">survfit</span>(<span class="fu">Surv</span>(t2, d3)<span class="sc">~</span>group,<span class="at">data=</span>bmt) <span class="sc">|&gt;</span> <span class="fu">summary</span>()</span>
<span id="cb21-474"><a href="#cb21-474" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-475"><a href="#cb21-475" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-478"><a href="#cb21-478" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb21-479"><a href="#cb21-479" aria-hidden="true" tabindex="-1"></a><span class="fu">survfit</span>(bmt.cox)</span>
<span id="cb21-480"><a href="#cb21-480" aria-hidden="true" tabindex="-1"></a><span class="fu">survfit</span>(bmt.cox, <span class="at">newdata =</span> <span class="fu">tibble</span>(<span class="at">group =</span> <span class="fu">unique</span>(bmt<span class="sc">$</span>group)))</span>
<span id="cb21-481"><a href="#cb21-481" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-482"><a href="#cb21-482" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-485"><a href="#cb21-485" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb21-486"><a href="#cb21-486" aria-hidden="true" tabindex="-1"></a>bmt.cox <span class="sc">|&gt;</span> </span>
<span id="cb21-487"><a href="#cb21-487" aria-hidden="true" tabindex="-1"></a>  <span class="fu">survfit</span>(<span class="at">newdata =</span> <span class="fu">tibble</span>(<span class="at">group =</span> <span class="fu">unique</span>(bmt<span class="sc">$</span>group))) <span class="sc">|&gt;</span> </span>
<span id="cb21-488"><a href="#cb21-488" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span>
<span id="cb21-489"><a href="#cb21-489" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-490"><a href="#cb21-490" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-491"><a href="#cb21-491" aria-hidden="true" tabindex="-1"></a><span class="fu"># Adjustment for Ties (optional)</span></span>
<span id="cb21-492"><a href="#cb21-492" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-493"><a href="#cb21-493" aria-hidden="true" tabindex="-1"></a>##</span>
<span id="cb21-494"><a href="#cb21-494" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-495"><a href="#cb21-495" aria-hidden="true" tabindex="-1"></a>At each time $t_i$ at which more than one of the subjects has an event,</span>
<span id="cb21-496"><a href="#cb21-496" aria-hidden="true" tabindex="-1"></a>let $d_i$ be the number of events at that time, $D_i$ the set of</span>
<span id="cb21-497"><a href="#cb21-497" aria-hidden="true" tabindex="-1"></a>subjects with events at that time, and let $s_i$ be a covariate vector</span>
<span id="cb21-498"><a href="#cb21-498" aria-hidden="true" tabindex="-1"></a>for an artificial subject obtained by adding up the covariate values for</span>
<span id="cb21-499"><a href="#cb21-499" aria-hidden="true" tabindex="-1"></a>the subjects with an event at time $t_i$. Let</span>
<span id="cb21-500"><a href="#cb21-500" aria-hidden="true" tabindex="-1"></a>$$\bar\eta_i = \beta_1s_{i1}+\cdots+\beta_ps_{ip}$$ and</span>
<span id="cb21-501"><a href="#cb21-501" aria-hidden="true" tabindex="-1"></a>$\bar\theta_i = \exp{\bar\eta_i}$.</span>
<span id="cb21-502"><a href="#cb21-502" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-503"><a href="#cb21-503" aria-hidden="true" tabindex="-1"></a>Let $s_i$ be a covariate vector for an artificial subject obtained by</span>
<span id="cb21-504"><a href="#cb21-504" aria-hidden="true" tabindex="-1"></a>adding up the covariate values for the subjects with an event at time</span>
<span id="cb21-505"><a href="#cb21-505" aria-hidden="true" tabindex="-1"></a>$t_i$. Note that </span>
<span id="cb21-506"><a href="#cb21-506" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-507"><a href="#cb21-507" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-508"><a href="#cb21-508" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb21-509"><a href="#cb21-509" aria-hidden="true" tabindex="-1"></a>\bar\eta_i &amp;=\sum_{j \in D_i}\beta_1x_{j1}+\cdots+\beta_px_{jp}<span class="sc">\\</span></span>
<span id="cb21-510"><a href="#cb21-510" aria-hidden="true" tabindex="-1"></a>&amp;= \beta_1s_{i1}+\cdots+\beta_ps_{ip}<span class="sc">\\</span></span>
<span id="cb21-511"><a href="#cb21-511" aria-hidden="true" tabindex="-1"></a>\bar\theta_i &amp;= \exp{\bar\eta_i}<span class="sc">\\</span></span>
<span id="cb21-512"><a href="#cb21-512" aria-hidden="true" tabindex="-1"></a>&amp;= \prod_{j \in D_i}\theta_i</span>
<span id="cb21-513"><a href="#cb21-513" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb21-514"><a href="#cb21-514" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-515"><a href="#cb21-515" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-516"><a href="#cb21-516" aria-hidden="true" tabindex="-1"></a><span class="fu">### Breslow's method for ties</span></span>
<span id="cb21-517"><a href="#cb21-517" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-518"><a href="#cb21-518" aria-hidden="true" tabindex="-1"></a>Breslow's method estimates the partial likelihood as</span>
<span id="cb21-519"><a href="#cb21-519" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-520"><a href="#cb21-520" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-521"><a href="#cb21-521" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb21-522"><a href="#cb21-522" aria-hidden="true" tabindex="-1"></a>L(\beta|T) &amp;=</span>
<span id="cb21-523"><a href="#cb21-523" aria-hidden="true" tabindex="-1"></a>\prod_i \frac{\bar\theta_i}{<span class="co">[</span><span class="ot">\sum_{k \in R(t_i)} \theta_k</span><span class="co">]</span>^{d_i}}<span class="sc">\\</span></span>
<span id="cb21-524"><a href="#cb21-524" aria-hidden="true" tabindex="-1"></a>&amp;= \prod_i \prod_{j \in D_i}\frac{\theta_j}{\sum_{k \in R(t_i)} \theta_k}</span>
<span id="cb21-525"><a href="#cb21-525" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb21-526"><a href="#cb21-526" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-527"><a href="#cb21-527" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-528"><a href="#cb21-528" aria-hidden="true" tabindex="-1"></a>This method is equivalent to treating each event as distinct and using the non-ties formula. </span>
<span id="cb21-529"><a href="#cb21-529" aria-hidden="true" tabindex="-1"></a>It works best when the number of ties is small. </span>
<span id="cb21-530"><a href="#cb21-530" aria-hidden="true" tabindex="-1"></a>It is the default in many statistical packages, including PROC PHREG in SAS.</span>
<span id="cb21-531"><a href="#cb21-531" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-532"><a href="#cb21-532" aria-hidden="true" tabindex="-1"></a><span class="fu">### Efron's method for ties</span></span>
<span id="cb21-533"><a href="#cb21-533" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-534"><a href="#cb21-534" aria-hidden="true" tabindex="-1"></a>The other common method is Efron's, which is the default in R.</span>
<span id="cb21-535"><a href="#cb21-535" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-536"><a href="#cb21-536" aria-hidden="true" tabindex="-1"></a>$$L(\beta|T)=</span>
<span id="cb21-537"><a href="#cb21-537" aria-hidden="true" tabindex="-1"></a>\prod_i \frac{\bar\theta_i}{\prod_{j=1}^{d_i}<span class="co">[</span><span class="ot">\sum_{k \in R(t_i)} \theta_k-\frac{j-1}{d_i}\sum_{k \in D_i} \theta_k</span><span class="co">]</span>}$$</span>
<span id="cb21-538"><a href="#cb21-538" aria-hidden="true" tabindex="-1"></a>This is closer to the exact discrete partial likelihood when there are</span>
<span id="cb21-539"><a href="#cb21-539" aria-hidden="true" tabindex="-1"></a>many ties.</span>
<span id="cb21-540"><a href="#cb21-540" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-541"><a href="#cb21-541" aria-hidden="true" tabindex="-1"></a>The third option in R (and an option also in SAS as <span class="in">`discrete`</span>) is the</span>
<span id="cb21-542"><a href="#cb21-542" aria-hidden="true" tabindex="-1"></a>"exact" method, which is the same one used for matched logistic</span>
<span id="cb21-543"><a href="#cb21-543" aria-hidden="true" tabindex="-1"></a>regression.</span>
<span id="cb21-544"><a href="#cb21-544" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-545"><a href="#cb21-545" aria-hidden="true" tabindex="-1"></a><span class="fu">### Example: Breslow's method</span></span>
<span id="cb21-546"><a href="#cb21-546" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-547"><a href="#cb21-547" aria-hidden="true" tabindex="-1"></a>Suppose as an example we have a time $t$ where there are 20 individuals</span>
<span id="cb21-548"><a href="#cb21-548" aria-hidden="true" tabindex="-1"></a>at risk and three failures. Let the three individuals have risk</span>
<span id="cb21-549"><a href="#cb21-549" aria-hidden="true" tabindex="-1"></a>parameters $\theta_1, \theta_2, \theta_3$ and let the sum of the risk</span>
<span id="cb21-550"><a href="#cb21-550" aria-hidden="true" tabindex="-1"></a>parameters of the remaining 17 individuals be $\theta_R$. Then the</span>
<span id="cb21-551"><a href="#cb21-551" aria-hidden="true" tabindex="-1"></a>factor in the partial likelihood at time $t$ using Breslow's method is</span>
<span id="cb21-552"><a href="#cb21-552" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-553"><a href="#cb21-553" aria-hidden="true" tabindex="-1"></a>::: smaller</span>
<span id="cb21-554"><a href="#cb21-554" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-555"><a href="#cb21-555" aria-hidden="true" tabindex="-1"></a>\left(\frac{\theta_1}{\theta_R+\theta_1+\theta_2+\theta_3}\right)</span>
<span id="cb21-556"><a href="#cb21-556" aria-hidden="true" tabindex="-1"></a>\left(\frac{\theta_2}{\theta_R+\theta_1+\theta_2+\theta_3}\right)</span>
<span id="cb21-557"><a href="#cb21-557" aria-hidden="true" tabindex="-1"></a>\left(\frac{\theta_3}{\theta_R+\theta_1+\theta_2+\theta_3}\right)</span>
<span id="cb21-558"><a href="#cb21-558" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-559"><a href="#cb21-559" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb21-560"><a href="#cb21-560" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-561"><a href="#cb21-561" aria-hidden="true" tabindex="-1"></a>If on the other hand, they had died in the order 1,2, 3, then the</span>
<span id="cb21-562"><a href="#cb21-562" aria-hidden="true" tabindex="-1"></a>contribution to the partial likelihood would be:</span>
<span id="cb21-563"><a href="#cb21-563" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-564"><a href="#cb21-564" aria-hidden="true" tabindex="-1"></a>::: smaller</span>
<span id="cb21-565"><a href="#cb21-565" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-566"><a href="#cb21-566" aria-hidden="true" tabindex="-1"></a>\left(\frac{\theta_1}{\theta_R+\theta_1+\theta_2+\theta_3}\right)</span>
<span id="cb21-567"><a href="#cb21-567" aria-hidden="true" tabindex="-1"></a>\left(\frac{\theta_2}{\theta_R+\theta_2+\theta_3}\right)</span>
<span id="cb21-568"><a href="#cb21-568" aria-hidden="true" tabindex="-1"></a>\left(\frac{\theta_3}{\theta_R+\theta_3}\right)</span>
<span id="cb21-569"><a href="#cb21-569" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb21-570"><a href="#cb21-570" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb21-571"><a href="#cb21-571" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-572"><a href="#cb21-572" aria-hidden="true" tabindex="-1"></a>as the risk set got smaller with each failure. The exact method roughly</span>
<span id="cb21-573"><a href="#cb21-573" aria-hidden="true" tabindex="-1"></a>averages the results for the six possible orderings of the failures.</span>
<span id="cb21-574"><a href="#cb21-574" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-575"><a href="#cb21-575" aria-hidden="true" tabindex="-1"></a><span class="fu">### Example: Efron's method</span></span>
<span id="cb21-576"><a href="#cb21-576" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-577"><a href="#cb21-577" aria-hidden="true" tabindex="-1"></a>But we don't know the order they failed in, so instead of reducing the</span>
<span id="cb21-578"><a href="#cb21-578" aria-hidden="true" tabindex="-1"></a>denominator by one risk coefficient each time, we reduce it by the same</span>
<span id="cb21-579"><a href="#cb21-579" aria-hidden="true" tabindex="-1"></a>fraction. This is Efron's method.</span>
<span id="cb21-580"><a href="#cb21-580" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-581"><a href="#cb21-581" aria-hidden="true" tabindex="-1"></a>::: smaller</span>
<span id="cb21-582"><a href="#cb21-582" aria-hidden="true" tabindex="-1"></a>$$\left(\frac{\theta_1}{\theta_R+\theta_1+\theta_2+\theta_3}\right)</span>
<span id="cb21-583"><a href="#cb21-583" aria-hidden="true" tabindex="-1"></a>\left(\frac{\theta_2}{\theta_R+2(\theta_1+\theta_2+\theta_3)/3}\right)</span>
<span id="cb21-584"><a href="#cb21-584" aria-hidden="true" tabindex="-1"></a>\left(\frac{\theta_3}{\theta_R+(\theta_1+\theta_2+\theta_3)/3}\right)$$</span>
<span id="cb21-585"><a href="#cb21-585" aria-hidden="true" tabindex="-1"></a>:::</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      <ul class="footer-items list-unstyled">
<li class="nav-item">
 Copyright 2023, Douglas Ezra Morrison
  </li>  
</ul>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>